### ISSUE TITLE
Uncaught Error: Class "Routes" not found

### ISSUE THREAD

**Issue by thangaraj-fuint** [timber/timber#2652] opened 2022-10-12 08:02 UTC
## Expected behavior
HTTP 200 state of site.

## Actual behavior
Site down with fatal error 500

## Steps to reproduce behavior
Update the Timber Version from 1.20.0 to 1.21.0

## What version of WordPress, PHP and Timber are you using?
WP Version: 6.0.2
PHP Version: 8.0
Timber Version: 1.21.0

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Downloaded the timber from github: https://github.com/timber/timber/releases/tag/1.21.0

**Comment by gchtr** [comment] 2022-10-12 08:07
If you download the release zip from the release page, that won’t work, because then you’re missing all Composer dependencies.

If you’ve installed Timber with Composer, then you should update it through Composer by running

```bash
composer update timber/timber
```

If you installed Timber as a plugin, I’m afraid you’ll have to wait a little longer, because we didn’t add that release to the [WordPress plugin repository](https://wordpress.org/plugins/timber-library/) yet. But we will, soon.

For the different ways of installing Timber, please follow the official [Setup Guide](https://timber.github.io/docs/getting-started/setup/#installation).

**Comment by thangaraj-fuint** [comment] 2022-10-12 08:30
Thanks for your qucik response @gchtr

**Comment by thangaraj-fuint** [comment] 2022-10-19 07:32
Hi @gchtr 
I've tried your new wordpress release 1.21.0
Everything looks good expect one thing.
tiwg's "attribute" function not working.
When I'm reverted the wordpress release to 1.20.0 "attribute" function working properly.
Could you able to check & let me know if there is any syntax changes ?

**Comment by gchtr** [comment] 2022-10-19 07:43
> tiwg's "attribute" function not working.
> When I'm reverted the wordpress release to 1.20.0 "attribute" function working properly.

What do you mean, it’s not working properly? Is there an error message? Is there no output?
If it doesn’t work right, it doesn’t have to be about the `attribute()` function, but it could also be about how objects work, because you work with a `profile` object here.

What’s `profile`? How does that object look like? I would need some code to help you here.

**Comment by thangaraj-fuint** [comment] 2022-10-19 07:52
@gchtr There is no error message.
I'm calling profiles.twig file using attribute().
The problem is not calling profiles.twig
Because profile object returns NULL :(
I'm not sure how it returns as null, If I reverted the plugin to old version means my object having values

**Comment by gchtr** [comment] 2022-10-19 10:13
To add formatted code blocks, you can use triple backticks ```:

<pre><code>```twig
{# Your Twig code here. #}
```</code></pre>

<pre><code>```php
// Your PHP code here.
```</code></pre>

**Comment by thangaraj-fuint** [comment] 2022-10-19 10:50
@gchtr Looks like importing a variable is not working, it returns null.
`{% import 'components/profiles.twig' as profile %}`

**Comment by thangaraj-fuint** [comment] 2022-10-19 11:23
@gchtr 

Here is the issue we found

// Importing twig as variable
{% import 'profiles.twig' as profile %}

// It is working
{{ profile.common('test content to be displayed') }}

// It is not working which is worked fine in twig 1.42.5
{{ attribute(profile, 'common', 'test content to be displayed') }}

// profile.twig contains this //
{% macro common( args ) %}
  {{ args }}
{% endmacro %}

Please take a look and let me know what is wrong here.

Thanks.

**Comment by mrfsrf** [comment] 2022-10-19 13:38
@thangaraj-fuint 
First, you'll get this error on previous versions as well:
**Argument 3 passed to Twig\Template::getAttribute() must be of the type array, string given**
Solution is
```php
{{ attribute(profile, 'common', ['test content to be displayed']) }}```

Second, you are importing wrong file. Don't know if you wrote code on the go...
import profile.twig, not profiles.twig

Hope that helps.

**Comment by thangaraj-fuint** [comment] 2022-10-19 13:58
@mrfsrf and @gchtr  Sorry my last comment was typo mistake.
Actually we've good on our code-base.
Rewriting my above comment, please take a look.

**Comment by mrfsrf** [comment] 2022-10-19 18:17
you are right. Looks like all macros from my site aren't working anymore. Have to dig more to find the cause.

**Comment by mrfsrf** [comment] 2022-10-19 21:13
https://github.com/twigphp/Twig/issues/2534
Looks like attribute can't be used to call macros anymore.

**Comment by mrfsrf** [comment] 2022-10-20 16:57
Looks like they upgraded to Twig v 2.x by mistake and because of that, reverted to previous version of plugin.

**Comment by thangaraj-fuint** [comment] 2022-10-21 03:13
@mrfsrf Yes, that was reason for my issue.

**Comment by thangaraj-fuint** [comment] 2022-11-22 11:40
Calling "text" on template "components/profiles.twig" from template "modules/events/contacts.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0.

// Importing twig as variable
{% import 'profiles.twig' as profile %}

// It is working.
{{ profile.text('test content to be displayed') }}

// It is working but this one throws deprecated warning
{{ attribute(profile, 'text', ['test content to be displayed']) }}

// profiles.twig contains this //
{% macro text( args ) %}
{{ args }}
{% endmacro %}

Seems like we cannot use dynamic method call?

**Comment by Levdbas** [comment] 2023-05-12 16:19
This particular issue is fixed with the new plugin release from october. @thangaraj-fuint , if you still run into your specific issue, please open a new issue with detailed information.

**Closed by Levdbas** 2023-05-12 16:19 UTC
Labels: has-patch
