### ISSUE TITLE
Fatal Error: Uncaught Logic Exception -- twig 3.10 deprecation @ timber/src/Twig.php

### ISSUE THREAD

**Issue by pgnd** [timber/timber#2994] opened 2024-05-11 15:12 UTC
with
```
composer show timber/timber
	name     : timber/timber
	descrip. : Create WordPress themes with beautiful OOP code and the Twig Template Engine
	keywords : templating, themes, timber, twig, wordpress
	versions : * 2.x-dev
	released : 2024-05-07, this week
	type     : library
```

and update to just-released Twig 3.10
```
composer show twig/twig
	name     : twig/twig
	descrip. : Twig, the flexible, fast, and secure template language for PHP
	keywords : templating
	versions : * v3.10.0
	released : 2024-05-11, today
	type     : library
	...
```

access to my site front-page, fires a new fatal error; e.g.,
```
( ! ) Fatal error: Uncaught LogicException: You must call "setEnvironment()" before calling "Twig\Extension\EscaperExtension::setEscaper()". in /srv/www/wp.app/web/app/themes/test-flynt/vendor/twig/twig/src/Extension/EscaperExtension.php on line 127

( ! ) LogicException: You must call "setEnvironment()" before calling "Twig\Extension\EscaperExtension::setEscaper()". in /srv/www/wp.app/web/app/themes/test-flynt/vendor/twig/twig/src/Extension/EscaperExtension.php on line 127
```

the call stack identifies,
```
.../Twig.php:558

	Twig\Extension\EscaperExtension->setEscaper( $strategy = 'esc_url', $callable = class Closure { } )
```

checking Timber src,
```
cat  ./vendor/timber/timber/src/Twig.php

	        if (\class_exists('Twig\Extension\EscaperExtension')) {
	            $escaper_extension = $twig->getExtension('Twig\Extension\EscaperExtension');
558	            $escaper_extension->setEscaper('esc_url', $esc_url);
	            $escaper_extension->setEscaper('wp_kses_post', $wp_kses_post);
	            $escaper_extension->setEscaper('esc_html', $esc_html);
	            $escaper_extension->setEscaper('esc_js', $esc_js);
	        }
	        return $twig;
	    }
```

and @ twig src,

	https://github.com/twigphp/Twig/blob/3.x/src/Extension/EscaperExtension.php#L127

the deprecation causing the error,
```
	...
114	    /**
	     * Defines a new escaper to be used via the escape filter.
	     *
	     * @param string                        $strategy The strategy name that should be used as a strategy in the escape call
	     * @param callable(Environment, string) $callable A valid PHP callable
	     *
	     * @deprecated since Twig 3.10
	     */
	    public function setEscaper($strategy, callable $callable)
	    {
	        trigger_deprecation('twig/twig', '3.10', 'The "%s()" method is deprecated, use the "Twig\Runtime\EscaperRuntime::setEscaper()" method instead (be warned that Environment is not passed anymore to the callable).', __METHOD__);

	        if (!isset($this->environment)) {
127	            throw new \LogicException(sprintf('You must call "setEnvironment()" before calling "%s()".', __METHOD__));
	        }
	        if (!isset($this->escaper)) {
	            throw new \LogicException(sprintf('You must call "setEscaperRuntime()" before calling "%s()".', __METHOD__));
	        }

	        $this->escapers[$strategy] = $callable;
	        $callable = function ($string, $charset) use ($callable) {
	            return $callable($this->environment, $string);
	        };

	        $this->escaper->setEscaper($strategy, $callable);
	    }
	...
```

**Comment by rmens** [comment] 2024-05-11 15:15
Just opened the same issue a few minutes earlier with a temporary fix https://github.com/timber/timber/issues/2993

**Comment by pgnd** [comment] 2024-05-11 15:34
drop back to last release, @

  https://github.com/twigphp/Twig/tags

```
composer require \
 timber/timber \
 twig/twig:"3.9.3"

composer show timber/timber | grep versions
	versions : * v2.1.0
composer show twig/twig | grep versions
	versions : * v3.9.3
```

cures, as expected

**Comment by Levdbas** [comment] 2024-05-13 09:38
Duplicate of #2993. We'll track in that ticket if any upgrades are needed in our codebase.

**Closed as not planned by Levdbas** 2024-05-13 09:38 UTC
