### ISSUE TITLE
Timber does not render on WP_DEBUG = false

### ISSUE THREAD

**Issue by sebas932** [timber/timber#2249] opened 2020-05-12 14:48 UTC
## Expected behavior

I expect from `Timber::render` to show the twig content even if the Wordpress is setup with `WP_DEBUG = false`, for production environments, but with `WP_DEBUG = true`, it works fine

## Actual behavior

Currently, it works if WP_DEBUG is `true`, but if WP_DEBUG is changed to `false`, there is no output, it shows a blank page, with nothing of the twig file rendered

## Steps to reproduce behavior

I´m using the docker Bitnami/wordpress image and just the following code:
**page-pagename.php**
``` 
if ( class_exists( 'Timber' ) ) {
  $context = Timber::context(); 
  Timber::render( get_stylesheet_directory() .'/templates/page-pagename.twig', $context );
}
```
**/templates/page-pagename.twig** 
``` 
{{ function('get_header') }}
 <div id="main-content" class="product-page">
   // content Here
 </div>
{{ function('get_footer') }}
```

## What version of WordPress, PHP and Timber are you using?

WordPress 5.4.1 
PHP 7.3
Timber 1.15.2

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Via plugin updater in WordPress dashboard

**Comment by sebas932** [comment] 2020-05-13 18:11
I found the following solution to this behavior

**page-pagename.php**
```
if ( class_exists( 'Timber' ) ) {
  $context = Timber::context(); 
  get_header();
  Timber::render( get_stylesheet_directory() .'/templates/page-pagename.twig', $context );
  get_footer();
}
```

**/templates/page-pagename.twig**
```
 <div id="main-content" class="product-page">
   // Twig content Here
 </div>
```

**Comment by sebas932** [comment] 2020-05-19 14:02
Hi @jarednova, yes, I did not mention that I´m using Divi (As parent theme) to create a custom Header and Footer, I think the issue could be related with this plugin. 
The weird issue here is that there is no error message, just a "No output" behavior

**Comment by jarednova** [comment] 2020-05-21 15:41
@sebas932 it's _likely_ that this then caused by Divi (as opposed to the server settings). Why? That's obviously what would be great to get to the root of.

We actually just incorporated a change into the next version (1.16.0) that has more error messages for when there's an invalid template: https://github.com/timber/timber/commit/28356bc18cb654d0451696925406435378cba471. This will be deployed to wp.org next week and might help us better isolate where the problem lies.

Have you checked out the header/footer files in the Divi theme to see if there's anything unique going on that could provide a clue?

**Comment by elvismdev** [comment] 2020-06-08 18:20
@jarednova I think this issue relates us back to https://github.com/timber/timber/issues/2084. 

While a PR was merged back in the day to fix #2084 we are still experiencing the same bug even with the latest Timber version 1.16.0. When `WP_DEBUG` is set to false, fronted pages just return a WSOD.

**Comment by jarednova** [comment] 2020-06-10 01:51
Oy. So just to confirm though #2084 didn't _break_ your problem. It just failed to resolve it, correct?

The rock and hard place that I'm in is that I simply can't replicate the issue. Given that @elvismdev and @sebas932 can — could one of you do a little [wolf-fencing](https://dl.acm.org/doi/10.1145/358690.358695) to determine where the problem lies? I'm pretty sure that if you could isolate the failure point the fix should be pretty clear (or at least, much easier to then replicate on my setup and reach a resolution)

**Comment by elvismdev** [comment] 2020-06-10 02:07
@jarednova that is correct, #2084 failed to resolve it.

**Comment by twentyfortysix** [comment] 2020-07-09 13:00
hi
I think I'm hitting similar problem.
latest WP, latest Timber, 
If I turn on the Yoast SEO and the define('WP_DEBUG', true); or define( 'WP_DEBUG_LOG', true );
all is fine, once I set all debug to false, the html head is cut off. All head above the {{ wp_head }} is gone.

I see this problem on one site only which is weird and so I suppose it has something to do with the PHP (PHP Version 7.2.20) or server setup as all my sites are based on one template framework and are in many many ways equal.

the only problem I'm able to trace out is 
```
[08-Jul-2020 16:30:04 UTC] PHP Notice:  is_feed was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in ../wp-includes/functions.php on line 5167
[08-Jul-2020 16:30:04 UTC] PHP Notice:  is_single was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in ../wp-includes/functions.php on line 5167
```

**Comment by jarednova** [comment] 2020-07-09 15:59
@twentyfortysix does the problem still occur if Yoast SEO is turned off?

**Comment by twentyfortysix** [comment] 2020-07-09 16:29
The answer is not that simple:

A. The head is cut off while:
Timber + wp_debug is false, Yoast is active

B. The head stays fine while:
Timber + wp_debug is true, Yoast is active

seams I'm not alone https://wordpress.org/support/topic/14-5-breaks-the-head/#post-13100729
(almost identical setup on different hosting works fine with PHP Version 7.3.19 - just for reference as I have no idea if the PHP version makes difference or not)

it is weird as normally if there is a problem the rest of the code is not visible, while here the previous code where the {{ fn('wp_head') }} is missing.

**Comment by jarednova** [comment] 2020-07-23 14:46
Very interesting. It looks like 14.6.1 is now out @twentyfortysix — does that resolve the issue?

**Comment by twentyfortysix** [comment] 2020-07-27 19:32
I don't know about 14.6.1 but Timber 1.17.0 does ;)

**Comment by jfaulk** [comment] 2020-09-11 18:58
I've been fighting the same problem of getting no output only when WP_DEBUG = false.

I've managed to narrow it down to my themes header.php.

If I delete the file or even just the `ob_start();` line then everything renders correctly.

Hopefully that helps the troubleshooting.

**Comment by jarednova** [comment] 2020-09-12 17:32
@jfaulk that's VERY interesting. That's a file/element not covered with any of the automated tests. Lemme see if there's stuff connected there

**Comment by jarednova** [comment] 2020-09-12 18:21
@twentyfortysix @sebas932. Unfortunately I'm still not able to replicate the issue, however @jfaulk's note is a very good clue to resolving it for your situations. The `header.php` & `footer.php` files included in the starter theme are hacks to help certain plugins that need/expect those files. To navigate around this, we rely on [PHP Output Buffering](https://www.php.net/manual/en/book.outcontrol.php) to "grab" Timber's content and hold it until the very end of the page in `footer.php` where it's finally sent to HTML.

I have two hunches ...
1) In certain setups `WP_DEBUG` interacts with PHP Output Buffering in a strange way that's either undocumented or specific to server configurations.
2) There's some kind of other error on your pages that's preventing `footer.php` from running or completing:
```php
$timberContext['content'] = ob_get_contents();
ob_end_clean();
$templates = array( 'page-plugin.twig' );
Timber::render( $templates, $timberContext );
```
For whatever reason, when `WP_DEBUG = true` WordPress might have a greater tolerance so that it's finishing execution (perhaps sending errors or warnings?). But when `WP_DEBUG = false` it's like "naw" and not getting to the very end. I'd recommend doing some debugging to verify if there's a place where there's a breakdown or following @jfaulk's suggestion and removing the various `ob_` calls to see what happens.

**Comment by twentyfortysix** [comment] 2020-09-17 13:54
Hey
I know this is of no help, but I have updated all I could and the problem is gone.
the log from last days when the debug was still true shows nothing more than:
`PHP Notice:  is_feed was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see ..wp-includes/functions.php on line 5167`

**Comment by luke-siedle** [comment] 2021-03-09 10:00
We have experienced a very similar issue relating to a 3DS redirect occurring with SagePay gateway in Woocommerce. It hooks into `woocommerce_receipt_` to echo some form html which submits to a 3DS url, but directly after that it runs `exit`. This was causing a completely blank page, and my only thought was it related to output buffering.

Eventually I modified the `page.php` as per the below, and now the echo + exit from the SagePay plugin works fine, and when not performing a redirect and just showing the checkout form. Feels a bit hacky but best I can come up with for now. 

Prior to the fix, when enabling WP_DEBUG true the flow worked correctly but did not show any warnings/errors, very strange. 

Fix I implemented below:

```
<?php

$context = Timber::context();

$timber_post = new TimberPost();

$context['post'] = $timber_post;


/**
 * IMPORTANT:
 * Deliberately run the_post / the_content
 * in isolation here, otherwise the twig context breaks
 * functionality like echoing html and exiting.
 * This seems to be related to output buffering in Timber.
 * This solves a bug with 3DS on SagePay, where the output
 * of the 3DS logic (form submit + redirect) is blank due to exit;
 *
 * The solution is to run the WP/Woocommerce code as normal
 * but buffer the output, remove it and inject into
 * the context. This lets the page flow naturally and exit
 * if required according to plugins,
 * or otherwise buffer its content.
 */

if( is_checkout() ){
  while(have_posts()){
    the_post();
    the_content();
  }
  wp_reset_query();

  // Get the contents of the output buffer and store it
  // (This is whatever has echoed onto the page, e.g. the checkout form)
  $content = ob_get_contents();

  // Remove the output entirely, so we can reconstruct the page
  ob_clean();

  // Add the checkout content into the timber context
  $context['checkout'] = $content;
}

// Simple render as normal in Timber
Timber::render('page.twig', $context);

```

**Comment by Levdbas** [comment] 2023-05-12 22:34
As this issue is now three years old, let's close this one. If anyone still runs into a similar issue, please report in a new issue.

**Closed by Levdbas** 2023-05-12 22:34 UTC
Labels: needs-info
