### ISSUE TITLE
TimberImage: Incorrect URL returned when image is stored off-server

### ISSUE THREAD

**Issue by TomSeldon** [timber/timber#429] opened 2014-12-26 21:39 UTC
When calling `get_src` (either directly or through typecasting a `TimberImage` instance to a string), the method doesn't take into account any of the standard WP methods for retrieving the image's URL (e.g. `wp_get_attachment_url` or `wp_get_attachement_image_src`) and instead goes off and does it's own thing for deriving the URL.

This works fine in what I would expect to be the majority of use-cases, however where other plugins are used to modify the location of files (in my case, moving uploaded files to an S3 bucket and then removing them from the server), this no longer works.

I suppose this is partially an issue with [the other plugin](https://wordpress.org/plugins/amazon-s3-and-cloudfront/), however they correctly apply a filter to the result of the above core method calls that would otherwise allow it to play nicely with other plugins. i.e. Calling `wp_get_attachment_url($id)` shows the Amazon S3 URL, not the (incorrect) location on the server.

Is there a reason why you went with a custom implementation over using a core method?

As a workaround for my case (and would work for anyone else affected by this issue), I just sub-classed `TimberImage` and overrode the `get_src` method:

``` php
<?php

namespace MyProject\PostType;


class Image extends \TimberImage {
    /**
     * @var int
     */
    private $iid;

    /**
     * @param int $iid
     */
    public function __construct($iid) {
        $this->iid = $iid;

        parent::__construct($iid);
    }

    /**
     * @param string|array $size - See http://codex.wordpress.org/Function_Reference/wp_get_attachment_image_src
     * @return array|bool|string
     */
    public function get_src($size = 'full') {
        return wp_get_attachment_image_src($this->iid, $size)[0];
    }
} 

```

I'm happy to put a PR up to correct this, but as I don't fully understand the reasoning behind the current implementation I'm reluctant to do so without hearing from you first.

Thanks (and thanks for the library, it's awesome!) :)

**Comment by tmoitie** [comment] 2015-03-19 10:03
Even with the change suggested here, the image resize filters aren't compatible with the S3 plugin either. It would be better if TimberImage was refactored to use the more traditional WordPress APIs for managing files.

**Comment by bryanknauber** [comment] 2015-04-10 07:37
I'm having this same issue (with, say, the URL returned by `post.thumbnail` not being the version on S3) – but I'm a bit too new to get subclassing `TimberImage` with @TomSeldon's code right. Most of my structure is still the starter theme. Any tips?

**Comment by j** [comment] 2015-04-23 22:36
Just pinging on this thread real quick... I'm pretty disappointed we spent our time using timber to find out that when going to production on a clustered AWS environment using the most popular amazon S3 plugin, that anything timber image related breaks.

Now we're stuck having to implement post specific resizing functionality / twig functions/filters to not use TimberImages. :(

This is a huge -1.

**Comment by aaemnnosttv** [comment] 2015-06-26 19:49
Just came across this issue while dealing with the same problem.  @TomSeldon has a good work around, but still - why doesn't Timber just use `wp_get_attachment_url` ?
@jarednova

**Comment by ivanjuras** [comment] 2015-06-27 15:04
Yeah, I think Timber should definitely use the built in API for these kinds of things; it will make it more compatible with other plugins.

**Comment by aaemnnosttv** [comment] 2015-07-28 20:43
Related #613.  Should be possible to work around this now without relying on inheritance.  Would be nice not to have to filter this though for something that would work if Timber used normal WP methods for fetching the full image src.

It seems this issue is limited to calls to fetching the src with no specified `$size`.  If there is a valid size passed, [it should use all the expected WP functions for returning the proper url](https://github.com/jarednova/timber/blob/dd42738879d35beab2d6ca0217ffc49ee194dc86/lib/timber-image.php#L99).

Simply changing the default parameter `$size = ''` to `$size = 'full'` for `src()` and `get_src()` methods doesn't work because 'full' isn't technically a size, so it doesn't exist within the `sizes` property array.

**Comment by kala725** [comment] 2015-09-29 10:37
In the new version of timber , the get_src function is deprecated in favour of src function.  So you can put this line
 `return wp_get_attachment_image_src($this->ID, $size)[0];`
just above the return statement of the src function in the timber/lib/timber-images file.  & It works.....

**Comment by connorjburton** [comment] 2016-03-02 12:54
Hi @TomSeldon is this still an issue, with @kala725's suggestion?

**Comment by TomSeldon** [comment] 2016-03-03 09:20
Hi @connorjburton, it's been a very long time since I've used Timber (or WordPress for that matter) so I'm not really sure.

If I'm not mistaken though, @kala725 is suggesting editing one of Timber's library files within your project. That might work fine as a quick patch, but really this sort of thing should be fixed within Timber itself (if it is indeed still an issue).

**Comment by connorjburton** [comment] 2016-03-03 09:38
Okay thanks, I'm just cleaning up issues.

No problem, I don't think this is an issue anymore due to `get_src` being a deprecated function, so I'm going to close this.

**Comment by blindstuff** [comment] 2016-03-08 03:43
Hi Everyone,

This is infact still an issue, even using the new `src` function instead of  `get_src`. When creating a TimberImage, the URL is incorrect if the S3 offload plug-in has been used.

In my case, I had to modify the library, as suggested by @kala725 to get `{{ Image(attachmentId).src }}` to work.

**Comment by connorjburton** [comment] 2016-03-08 08:16
Hi @blindstuff - thanks for this, will re-open, could you provide me with more information, what is wrong with the URL when using that plugin?

**Comment by blindstuff** [comment] 2016-03-08 14:38
Hi @connorjburton,

I'm using [this](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) plug-in; when a file is uploaded to the media gallery via the wp-admin, it will take the images, move them to an AWS S3 bucket i've setup, and delete them from the application server.

I'm not sure about the details of the implementation on that side, but the bucket and URL are saved in a serialized manner, i'm under the impression that their implementation catches the traditional functions for getting attachments in WP and desiralizes to return the correct URL. During this time, the GUID for the image will still point to server itself instead of S3. All the methods used by timber do not take this into account.

I've modified, as was suggested, `src` in timber/lib/timber-images to always `return wp_get_attachment_image_src($this->ID, $size)[0];` and it does return the correct URL. Of course, side-effects need to be checked, but it seems to work in all cases from the limited testing i've done.

`new TimberImage(3726);`
Will return:
`TimberImage Object
(
    ...
    [ID] =&gt; 3726
    ...
    [amazonS3_info] =&gt; a:3:{s:6:"bucket";s:25:"BUCKET_NAME";s:3:"key";s:44:"wp-content/uploads/2015/04/mobile-alerts.png";s:6:"region";s:0:"";}
    [_wp_attachment_metadata] =&gt; a:5:{s:5:"width";i:27;s:6:"height";i:30;s:4:"file";s:25:"2015/04/mobile-alerts.png";s:5:"sizes";a:0:{}s:10:"image_meta";a:11:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";s:11:"orientation";i:0;}}
    ...
    [guid] =&gt; http://localhost:8080/wp-content/uploads/2015/04/mobile-alerts.png
)
`
You can see what i'm talking about the GUID and the S3 URL.

In twigs `{{ Image(ID).src }}` returns
before the modification:
`http://localhost:8080/project- name/wp-content/uploads/2016/03/alert-triangle-red-128.png `
After the modification:
`http://bucket-name.s3.amazonaws.com/wp-content/uploads/2016/03/alert-triangle-red-128.png `

Hope this is enough information, if you need anything else let me know.

**Comment by ollisal** [comment] 2016-03-11 07:06
Note also the width and height fields, which are in the _wp_attachment_metadata. Currently TimberImage.width and .height return nothing for S3 images, even if you override the src, as the dimensions code tries to read the image dimensions from the image file in the filesystem: https://github.com/jarednova/timber/blob/master/lib/timber-image.php#L122

Thus when running WP in a cloud environment it's impossible to pre-define width= and height= attributes for <img> in your HTML, which would speed up page rendering.

Probably would be better performance-wise as well to stop reading image files from FS and just read them from the WP attachment object loaded from DB. The attachment metadata is already loaded in get_image_info: https://github.com/jarednova/timber/blob/master/lib/timber-image.php#L156

**Comment by corysimmons** [comment] 2016-11-11 19:02
What's the status of this?

`return wp_get_attachment_image_src($this->ID, $size)[0];` seems to fix this, but if it were that easy, I'm sure it'd be merged by now. Can a maintainer update us or can we get this merged?

It'd be nice if Timber worked with the plethora of WP S3 plugins out of the box.

**Comment by blindstuff** [comment] 2016-11-11 19:14
@corysimmons I'm still replacing that line manually every time I update timber. I'm also interested in seeing if there is any news on an official fix.

**Comment by corysimmons** [comment] 2016-11-11 21:06
@blindstuff That's pretty brutal whenever I need to hand the site off to the client, "Hey, don't update your site because the framework I used on it will break the imagery."

I'm really not sure what to do but the fact that Timber seems incompatible with WP's official API puts me off of using it again.

This seems like a pretty common issue as well...

**Comment by tvanantwerp** [comment] 2017-01-11 14:58
I really want to see this issue solved, so I've posted a [$100 bounty](https://www.bountysource.com/issues/7301361-timberimage-incorrect-url-returned-when-image-is-stored-off-server). Six month time limit.

**Comment by jarednova** [comment] 2017-01-11 15:05
@tvanantwerp — well that will get our attention! I'm working on #1279 and #1286 right now; so I'd love to see PRs on this (with tests, please)!

**Comment by moreguppy** [comment] 2017-02-07 11:24
Ran into this issue recently, and found an up-to-date fix over on #1131 

```
// Add this to functions.php
function fix_timber_s3_src( $src, $ID ) {
    $size = '';
    $attachment_src = wp_get_attachment_image_src($ID, $size)[0];
    $fixed_src = $attachment_src ? $attachment_src : $src;
    return $fixed_src;
}
add_filter( 'timber_image_src', 'fix_timber_s3_src', 10, 2 );
```

**Comment by tvanantwerp** [comment] 2017-02-07 14:32
I've tried the fix posted by @moreguppy before, but it breaks thumbnail size functionality with `$size = '';`. I'm not sure myself if there's a way to rewrite it to get around that.

**Comment by jarednova** [comment] 2017-02-10 16:04
@moreguppy @tvanantwerp Now that version 1.2.2 is done, i'm working on this guy. I'm trying to setup my environment to match the error and potential solutions that are posted here and in #1131. I have everything setup with S3 and the plugin (see sample image here uploaded through WP).

Here's what I've found so far:

### For loading images (no resize):

#### Current Functionality
Calling `{{ post.thumbnail.src }}` returns the local URL (like 'http://mysite.com/wp-content/2017/02/myimage.jpg')

#### With Filter Patch
Calling `{{ post.thumbnail.src }}` returns the AWS URL (like 'http://s3.amazonaws.com/timbertester/wp-content/uploads/2016/06/10104307/myimage.jpg')

### For loading image (WITH resize):
#### Current Functionality
Calling `{{ post.thumbnail.src }}` returns the **resized** local URL (like 'http://mysite.com/wp-content/2017/02/myimage1920x1000-c-top.jpg')

#### With Filter Patch
Calling `{{ post.thumbnail.src }}` returns a resized local URL, but one that appears to have been sideloaded from AWS (like 'http://mysite.com/wp-content/uploads/2017/02/3be9f9cf6271b8bdb888a10c17ed95b3-1920x1000-c-top.jpg')

... can you confirm that this is what you're seeing too? Ideally, we should always get an AWS URL back even when resizing is on, correct?

**Comment by tvanantwerp** [comment] 2017-02-10 16:54
I'm not able to reproduce the same output you're seeing, nor what I've already experienced. Here's what I'm getting when I test it now:

[WP Offload S3 Lite](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) and Timber 1.22 without filter

| Dump | Result |
| --- | --- |
| {{dump(post.thumbnail.src)}} | "http://localhost/wp-content/uploads/2017/02/IMG_9998.jpg" |
| {{dump(post.thumbnail.src('thumbnail'))}} | "https://custom-s3-domain.com/20170210113619/IMG_9998-150x150.jpg" |
| {{dump(post.thumbnail.src('medium'))}} | "https://custom-s3-domain.com/20170210113619/IMG_9998-300x200.jpg" |
| {{dump(post.thumbnail.src('large'))}} | "https://custom-s3-domain.com/20170210113619/IMG_9998-1024x683.jpg" |

[WP Offload S3 Lite](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) Timber 1.22 with filter from @moreguppy

| Dump | Result |
| --- | --- |
| {{dump(post.thumbnail.src)}} | "https://custom-s3-domain.com/20170210113619/IMG_9998.jpg" |
| {{dump(post.thumbnail.src('thumbnail'))}} | "https://custom-s3-domain.com/20170210113619/IMG_9998-150x150.jpg" |
| {{dump(post.thumbnail.src('medium'))}} | "https://custom-s3-domain.com/20170210113619/IMG_9998-300x200.jpg" |
| {{dump(post.thumbnail.src('large'))}} | "https://custom-s3-domain.com/20170210113619/IMG_9998-1024x683.jpg" |

This is not the same behavior I've encountered previously--maybe upgrading to 1.22 made a difference. The result of `post.thumbnail.src` without the filter is obviously still wrong. What I don't understand is why everything else is now correct. Previously, the filter only ever returned the original size from S3 and no filter would never return anything from S3.

These are my WP Offload S3 Lite settings in case it makes a difference.

![image](https://cloud.githubusercontent.com/assets/2487968/22835686/9785356c-ef87-11e6-88c1-f597c1daaff5.png)

**Comment by jarednova** [comment] 2017-02-10 17:09
1.2.2 contained a ton of image refactoring — looks like a big chunk of the issues here might have been solved! I've got #1320 going that should hopefully resolve the issues with `{{ post.thumbnail.src }}` (without any size info passed).

Handling with the resize filter is gonna be its own beast, but I've got a pretty good idea how to accomplish that. I'll at least give it a shot and _see_ if my head explodes

**Comment by jarednova** [comment] 2017-02-10 17:10
@tvanantwerp thanks for posting the really detailed rundown by the way — that _really_ helps as I test and fix this

**Comment by jarednova** [comment] 2017-02-20 16:18
@tvanantwerp I think that both this and #1321 are now resolved, can you confirm?

**Closed** 2017-02-22 17:34 UTC
Labels: confirm-and-close, has-patch

**Comment by timvandijck** [comment] 2017-06-22 14:40
@jarednova this still seems to be a problem? |resize() still returns the normal URL instead of an offloaded one.

**Comment by guyroutledge** [comment] 2017-07-03 21:28
I've just come across this thread as I'm in the process of testing out Offload S3 on my existing Timber site (running Timber v1.2.4 without composer). Uploading to S3 works find but resized images in twig templates use a local file "sideloaded" from S3.

I see an experimental Timber 1.3.2 has been released. Any chance there's a fix for working with S3 in there?

**Comment by aaemnnosttv** [comment] 2017-07-04 09:36
The original issue here was that Timber image methods were not using core functions for obtaining URLs (see https://github.com/timber/timber/pull/1320/files) which has been fixed.

Using Timber's `resize` function creates the new file locally, but will not get uploaded to S3 as it is not associated with the attachment it came from, nor is it an attachment itself. WP Offload S3 only supports handling media library items and their respective registered image sizes. We're planning on adding support for non-media files in the future but until then, there probably isn't a good solution.

I like the resize function but I think its more useful during initial development to help you figure out what image sizes you need. Then you can register those sizes and replace the resize usage with the named size. I realize that doesn't scale well for lots of different sizes, but image sizes are an important part of the extensibility of media in WordPress.

**Comment by timvandijck** [comment] 2017-07-06 14:34
@aaemnnosttv I completely understand the issue and I'm happy to hear that a solution is something that might come in the future.

However for now it would probably be a good idea to have a warning in the documentation for resize(). We only stumbled on this when we wanted to offload the images of a site which media library was becoming huge and we lost valuable time converting all resize() usages to WP image sizes and generating thumbs.

**Comment by aaemnnosttv** [comment] 2017-07-06 19:17
I probably should have clarified in my comment that I'm a developer on WP Offload S3 :)
I'm not sure that it's Timber's responsibility to make it work with our plugin though, but maybe that's not what you're suggesting. I agree that adding a note to the Timber docs may be helpful for some though.

**Comment by maxleistner** [comment] 2018-10-17 06:31
Any news on this problem? I still have this problem and the filter mentioned above does not work.

**Comment by johnnypea** [comment] 2018-11-29 13:48
Anybody has a solution for this?

**Comment by kemmerly** [comment] 2019-02-14 21:49
Another bump. I'm having issues using S3 via Large FS on WP Engine. Twig image tags with resize just pull the original thumb src. Any help or updates would be greatly appreciated.

**Comment by gchtr** [comment] 2019-02-18 22:46
## Why does the resize filter not work with CDNs?

I just want to repeat here what @aaemnnosttv said [in an earlier comment](https://github.com/timber/timber/issues/429#issuecomment-312832338) in this thread:

> Using Timber's `resize` function creates the new file locally, but will not get uploaded to S3 as it is not associated with the attachment it came from, nor is it an attachment itself. WP Offload S3 only supports handling media library items and their respective registered image sizes. We're planning on adding support for non-media files in the future but until then, there probably isn't a good solution.

**The `resize()` filter doesn’t work with CDNs**. WordPress doesn’t know about resized Timber image sizes. Consequently, any plugin that adds CDN support doesn’t either.

## Is there a workaround?

The current workaround is to use WordPress image sizes proposed by @aaemnnosttv:

> I like the resize function but I think its more useful during initial development to help you figure out what image sizes you need. Then you can register those sizes and replace the resize usage with the named size.

This means that you can add an image size through [`add_image_size()`](https://developer.wordpress.org/reference/functions/add_image_size/) and then reference it with `src()`:

```twig
<img src="{{ post.thumbnail.src('my_custom_size') }}">
```

## Will it work in the future?

Short answer: probably not with the current API.

> I'm not sure that it's Timber's responsibility to make it work with our plugin though, but maybe that's not what you're suggesting. I agree that adding a note to the Timber docs may be helpful for some though.

I’ve created a [pull request](https://github.com/timber/timber/pull/1925) to document the limitations.

I’d say Timber should eventually find a way to add support for hooking into WordPress core image functionality. This is rather complex and I guess there’s no way around using a central registry for images that hooks into all the relevant WordPress functions – like elevated WordPress image sizes. This is the idea behind [Timmy](https://github.com/mindkomm/timmy), though we didn’t test it with a CDN yet.

**Comment by duplich** [comment] 2020-02-05 13:46
As I am also using `|resize()` filter often and it feels veery comfortable while working on an early stage. But I am not sure if this must work in a Production environment with CDN. I guess the architecture would be the following scenario: 

1. Whenever you use a different `|resize()` filter for the image file
2. TImber/Offload S3 fetch the original image from CDN
3. Timber/Offload S3 resize the Image
4. Timber/Offload S3 uploads the Image to your CDN
5. TImber populates the src tag with the new `src="cnd.s3.examplesite.com/image-new-size.jpg"` and voila your site has Image served from CDN...

**Downside:** 
This would require Timber being aware of, and communicate with Offload S3 or any other CDN plugin, as well as managed caching because the process of downloading the original, resizing and uploading the new file is pretty slow on the network and serving image from a local directory is, in this case, simply faster. Unless you set up the caching that fires upon the first call for each new `resize()` filter used. 

**Questions raised:** 
1. What happens with created files after removing the filter from a template?
2. Does WordPress know of the new files if they are not created by `add_image_size()` (probably not)
3. What is the downside of using `|resize` for prototyping and `add_image_size()` for production

I think @gchtr actually provided a good solution and I think I will use it this way.
