### ISSUE TITLE
Wordpress Media Libary not showing up

### ISSUE THREAD

**Issue by mathis89** [timber/timber#889] opened 2016-03-07 13:38 UTC
Hi all,

I've got the problem that the Wordpress media library (in grid view) is not showing up and the grey loading circle is spinning around the whole time, while the timber plugin is activated.
I already found out, that there's no problem when the media library is switched to list view.
The problem also occurs when I want to add an image to a post.

I'm using WordPress 4.4.2.

**Comment by connorjburton** [comment] 2016-03-07 14:02
Hi @mathis89 - could you tell me what the php error is? I can't seem to replicate this.

Thanks.

**Comment by connorjburton** [comment] 2016-03-15 08:49
Hi @mathis89 - I'm going to close this for now as I can't seem to replicate this issue.

If you do manage to get more info I will happily re-open.

**Comment by developer-lindner** [comment] 2016-03-15 13:49
The issue arised at all latest projects we were going to use Timber. (It's a very very plugin by the way!)
But it breaks the XHR Response in the Media Library (Grid View) somehow:

The response if Timber is activated:
`<?php{"success":true,"data":[{"id":175,"title":"kunstgallery11b","filename":"kunstgallery11b.jpg" ...`

And if not:
`{"success":true,"data":[{"id":175,"title":"kunstgallery11b","filename":"kunstgallery11b.jpg" ...`

**Comment by connorjburton** [comment] 2016-03-15 14:00
Hm, that is strange, does this happen with a default wordpress theme and all plugins except Timber disabled?

Also have you tried this on another server and could you provide info on your server setup.

Thanks

**Comment by developer-lindner** [comment] 2016-03-15 14:08
Interesting!
With one of those default themes (twentysixteen) it's gone. 
So it should be related to functions.php or utility-functions.php (which extends prior class in functions.php).

functions.php:
`class WebSite extends TimberSite {`

utility-functions.php:
`class Utilities extends WebSite {`

**Comment by connorjburton** [comment] 2016-03-15 14:11
Could you post gists of those two classes? Thanks

**Comment by connorjburton** [comment] 2016-03-15 14:12
Or actually gists of the whole file(s) they are in would be good, as there may be rogue tags.

**Comment by developer-lindner** [comment] 2016-03-15 14:16
I already found the cause which is kinda ridiculous... 

The issue was introduced by:
`add_action( 'init', array( $this, 'register_shortcodes' ) );`

Which goes to
`function register_shortcodes() {
        require_once __DIR__. '/shortcodes.php';
	}`

And shortcodes.php:
`<?php`

It's the emptied php file in the end. Sry for the trouble!

**Comment by connorjburton** [comment] 2016-03-15 14:19
No problem :)

**Closed by connorjburton** 2016-03-15 14:19 UTC
Labels: needs-info
