### ISSUE TITLE
Twig cache fails to save on WP Engine

### ISSUE THREAD

**Issue by anrw** [timber/timber#1311] opened 2017-01-29 07:07 UTC
### Expected behavior
Cache is saving correctly

### Actual behavior
For some reason Twig cache in many cases fails to save. The issue happens only on Live. On Staging everything is working fine.

![alt tag](http://i.imgur.com/PLfy48k.jpg)

You can see that sometimes caching is generated correctly, i.e. it has ".php" extension, however in other cases the string is too long. It should be 64 chars + ".php", but it 68-69 and without extension. In this case Timber is not able to read cache and tries to save it again and again.

This screenshot is from version 0.21.10, however on 1.2.1 the issue still exists.

### Error Log
PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/path/wp-content/themes/client/vendor/timber/timber/cache/twig/90/90ae569d9163ddb1bc7868bd2ce3387425f685cc53dc3e88deda1f8fc065bc4b.php".' in /path/wp-content/themes/client/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:75

Stack trace:
#0 /path/wp-content/themes/client/vendor/twig/twig/lib/Twig/Environment.php(452): Twig_Cache_Filesystem->write('/path/wp...', '<?php??/* /path/...')
#1 /path/wp-content/themes/client/vendor/twig/twig/lib/Twig/Environment.php(362): Twig_Environment->loadTemplate('/path/wp...')
#2 /path/wp-content/themes/client/vendor/timber/timber/lib/Loader.php(74): Twig_Environment->render('/path/wp...', Array)
#3 /path/wp-content/themes/client/vendor/timber/timber/lib/Timber.php(286): Timber\\Loader->render('/path/wp.. in /path/wp-content/themes/client/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 75

### What version of WordPress, PHP and Timber are you using?
WordPress 4.7.2, Timber: 1.2.1, PHP: 5.5.9

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by anrw** [comment] 2017-01-29 07:10
I know that this most likely related to server configuration, however wanted to ask what can cause such behaviour?

**Comment by jarednova** [comment] 2017-02-02 20:59
@anrw maybe a permissions issue? check that directory to make sure it's writeable by WP process. Setting it to `777` is a good way to at least verify that it's a permission issue (obviously, don't _leave_ it as `777`) but that can at least help us determine whether that's the root cause

**Comment by anrw** [comment] 2017-02-06 09:05
Thanks @jarednova, unfortunately this is not the reason. All directories have 775, moreover - sometimes cache saves. You can see it on my screenshot: highlighted file was successfully saved. Near it there are files that failed to save. 

![alt text](http://i.imgur.com/MROMMFZ.jpg)

If you look at this screenshot, you will see that hash is mostly the same (first 63 chars). Sha256 generates 64 chars and I am not sure why the last char is different and also (in failed cases) produces plus 6 random chars.

So that means that `file_put_contents` works, the file itself is not broken too. However looks like it fails on `rename` step. In this case it can't set correct chmod and can't read the file, returning " Internal Server Error 500 No response "

**Comment by nishan-mills** [comment] 2017-11-28 10:20
I am seeing this error as well; this was after I had enabled twig caching. Any progress on this issue?

`PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/nas/content/live/{proj}/wp-content/plugins/timber-library/cache/twig/0c/0cc33aea03fbc32b0545b2261cb54e5cfa127ff2daa0f3567a7a4e3bfd7616d0.php".' in /nas/content/live/{proj}/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Cache/Filesystem.php`

**Comment by wizardist** [comment] 2017-11-28 10:25
I triaged this bug with WPEngine guys. I'm not using Timber, but faced the same problem with Twig on WPEngine.

So, here's the deal. Due to security limitations, 600 permissions are assigned to newly created `*.php` files, which leads to the temporary file unable to be moved to the target filename.

Creating `*.html` cache files instead would fix the issue. The solution is to extend `\Twig_Cache_Filesystem` and feed the new implementation to Twig.

HTH

**Comment by mahagr** [comment] 2017-11-28 11:16
Or you can just use another folder for storing twig files. See https://github.com/gantry/gantry5/issues/1155

**Comment by nishan-mills** [comment] 2017-11-30 08:57
Thanks @mahagr so it seems that you need to use the /tmp/ folder on wpengine, so you would potentially create a folder with a random enough name that you can refer later on. For example; /tmp/<guid>/cache/timber. This folder is on the main server and not within your wpengine instance so you won't be able to access it directly and you don't have any control over when it will be cleared. Going for a more robust solution would be doing what @wizardist had suggested.

**Comment by terenceneedssurgery** [comment] 2018-01-02 12:51
@wizardist you are correct but a slight correct from my support conversation with WPEngine today;

Newly created `.php` files are created with 644 - if you were to add one via ftp you will see this. 

Newly created files without an extension are created with 600. At this point as you say php cannot write via the traditional `file_put_contents` or `rename` functions as it tries to below:

https://github.com/twigphp/Twig/blob/fd98722d15996561f598f9181dbcef8432e9ff85/lib/Twig/Cache/Filesystem.php#L63

Files are created without an extension before renaming to a php file extension.

So two solutions; find a way to create these files with an extension with `.html`, or `.php` by extending `\Twig_Cache_Filesystem` as you say, or don't use WPEngine. I know which one i prefer, unfortunately my client prefers the least easy solution.

**Comment by marcell-ferenc** [comment] 2018-04-05 19:59
@terenceneedssurgery, @wizardist  I have some additional info that I am faced to and is related to the described problem: I am using [themosis framework](https://framework.themosis.com/) in a classic WP project hosted by WPEngine. Themosis stores temporary twig and cache files in `/wp-content/storage/twig`.

As a quick and dirty investigation in `\Twig_Cache_Filesystem` when i test `file_put_contents($tmpFile, $content)` it evaluates to `true` such as `rename($tmpFile, $tmpFile . '.new')` for example. 

For `file_put_contents($tmpFile . '.php', $content)` I receive: 

> Warning: **_wpe_old_file_put_contents**(/nas/content/live/...YPUG.php): failed to open stream: Permission denied in /opt/nas/www/**common/production/php_prevent_flock.php** on line 58

From [WPEngine troubleshooting](https://wpengine.com/support/troubleshoot-wordpress-wp-engine-error-log/):

> You could also see an error like this **if a plugin or theme is trying to do something that’s not allowed on our platform** or is **trying to access a file/directory it shouldn’t have access to**:

> PHP Warning:  file_put_contents(/nas/wp/www/cluster-2349/yourblog/wp-content/cache/autoptimize/autoptimize_b1b3a88cd5d8cfd4d1b5a716beef375a.php) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /nas/wp/www/common/production/php_prevent_flock.php on line 21...

Also `rename($tmpFile, $tmpFile . '.php')`:

`Warning: rename(/nas/content/live/...x5b9Go,/nas/content/live/...x5b9Go.php): Permission denied in .../wp-content/plugins/themosis-framework/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 68`

**Comment by gchtr** [comment] 2023-05-03 19:34
I’m closing this. If anybody has a solution to solve this, feel free to share.

**Closed by gchtr** 2023-05-03 19:34 UTC
Labels: question, needs-info
