### ISSUE TITLE
Twig filter called filter doesn't work

### ISSUE THREAD

**Issue by palmiak** [timber/timber#2111] opened 2019-11-17 23:57 UTC
## Expected behavior

https://twig.symfony.com/doc/2.x/filters/filter.html
Let's use the first example
```
{% set sizes = [34, 36, 38, 40, 42] %}

{{ sizes|filter(v => v > 38)|join(', ') }}
{# output 40, 42 #}
```

## Actual behavior

We get empty, blank, nothing :)

## Steps to reproduce behavior

Just paste the example above.
## What version of WordPress, PHP and Timber are you using?

Twig 1.12.1 (test on 1.12.0 too), PHP 7.3, WP 5.2.x

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Via composer

I thought for a moment it's a problem with arrow function but I didn't had a problem with `|sort` so to be honest I don't have a clue why it's not working and on the hand it doesn't show any error.

**Comment by xdevelx** [comment] 2019-11-18 21:00
Duplicate of #2010

**Comment by xdevelx** [comment] 2019-11-18 21:03
Duplicate of #2010

**Closed** 2019-11-18 23:06 UTC
