### ISSUE TITLE
Starter theme for WooCommerce

### ISSUE THREAD

**Issue by JosefJezek** [timber/timber#79] opened 2013-10-16 11:41 UTC
Could you make Starter theme for WooCommerce?

**Comment by rzeka** [comment] 2015-02-05 08:29
Is someone still trying to do this? I've got 2 shops already using Timber, but each template has its own quirks and is modified just for that single shop.
If I can find some spare time, I'll try to adapt templates so they can work with any shop and any settings. Thanks to @asecondwill for those 3 gists. Without them I'd have failed

**Comment by lmartins** [comment] 2015-02-05 09:08
Im building something that I still need to abstract to something reusable. Mind you, im taking a conservative approach, where most stuff still loads with the standard actions from woocommerce.

**Comment by bikeatefoucault** [comment] 2015-02-10 19:23
About to get started on some Woocommerce enabled sites and considering using Timber/Twig for them.

 Seems like there's enough people here to help out with a project, does anybody want to start a repo with what they have so far and we can all get cracking on it?

**Comment by lmartins** [comment] 2015-02-12 10:14
Hey Alan,

I've been building a few WooCommerce projects using Timber and it's brilliant. Having already got some help from the posts above and @jarednova on a few occasions, I might be able to help. Mind you, the first step is to get some experience with building normal wordpress installs using Timber and for that the Wiki is your best choice.  
Once you get accustomed with the way things are structured, then move on into WooCommerce.

Then, you'll have one big decision to make, either you go "woocommerce's way", that is your templates are essentially loading WooCommerce hooks, or you'll try to build everything from scratch. I would advise for the first option, which is what im using. It allows you integrate WooCommerce add-ons without issues, upgrading Woo without issues, while still allowing for template customisation if that's what you're after.

My code right now is structured for child-themes, but i'll try to make a quick repo with sample code for a normal theme with Timber/WooCommerce integration. The code posted above should get you started anyway.

**Comment by JosefJezek** [comment] 2015-02-12 10:19
See https://press.codes/downloads/maera-woocommerce/

**Comment by bikeatefoucault** [comment] 2015-02-13 00:39
@lmartins,

Thanks for the response. Everything posted so far should be a big help moving forward.

**Comment by rbvea** [comment] 2015-02-20 03:42
Looks like @jarednova has a wiki page up, anybody want to put in a couple of pointers? https://github.com/jarednova/timber/wiki/WooCommerce-Integration

**Comment by lmartins** [comment] 2015-02-21 08:59
I've added some information of how I approach this, including some tips I've got from @jarednova about products context within the loop.

**Comment by eleirgulen** [comment] 2015-03-09 09:28
I have tried to follow the instructions here: https://github.com/jarednova/timber/wiki/WooCommerce-Integration

The issue is that all products on the category/archive pages output the same images, and also the same "post id".

The following code from tease-product-twig: 
```
<article {{ fn('post_class', ['$classes', 'entry'] ) }}>
```
is showing like this in my code:
```
<article class="post-28 product type-product status-publish has-post-thumbnail $classes entry purchasable product-type-simple product-cat-fossiler instock">
```
All the text, prices etc are correct but the article class and the images is the same in the loop.

I have included this code in functions.php
````
function timber_set_product( $post ) {
    global $product;
    if ( is_woocommerce() ) {
        $product = get_product($post->ID);
    }
}
```

Any idea how to fix this?

**Comment by lmartins** [comment] 2015-03-09 09:37
Are you calling the `timber_set_product` in the tease product twig file?

**Comment by eleirgulen** [comment] 2015-03-09 09:41
this is my tease-product.twig

```
<article {{ fn('post_class', ['$classes', 'entry'] ) }}>

    {{ fn('timber_set_product', post)}}

    <div class="Media">

        {% if showthumb %}
            <div class="Media-figure {% if not post.thumbnail %}placeholder{% endif %}">
                <a href="{{post.link}}">
                    {% if post.thumbnail %}
                        <img src="{{ post.thumbnail.src|resize(post_thumb_size[0], post_thumb_size[1]) }}" />
                    {% else %}
                        <span class="thumb-placeholder"><i class="icon-camera"></i></span>
                    {% endif %}
                </a>
            </div>
        {% endif %}

        <div class="Media-content">
            {% do action('woocommerce_before_shop_loop_item_title') %}
            {% if post.title %}
                <h3 class="entry-title"><a href="{{post.link}}">{{ post.title }}</a></h3>
            {% else %}
                <h3 class="entry-title"><a href="{{post.link}}">{{ fn('the_title') }}</a></h3>
            {% endif %}
            {% do action( 'woocommerce_after_shop_loop_item_title' ) %}
            {% do action( 'woocommerce_after_shop_loop_item' ) %}
        </div>

    </div>

</article>
```

**Comment by lmartins** [comment] 2015-03-09 09:46
That's weird, apparently it is how it was supposed to be. 
Please check the what is being passed in the `post` object to `timber_set_product`

**Comment by eleirgulen** [comment] 2015-03-09 11:22
I did a var_dump($post); inside the timber_set_product functions in functions.php

You can have a look at the output here:
http://woocommerce-5452-12198-27730.cloudwaysapps.com/

**Comment by lithiumlab** [comment] 2015-04-12 12:54
Hi; 
I'm struggling a bit trying to get out woocommerce price formatted ($49.99) instead of 49.
what am i missing? the filter returns the _price value without modifying it.
I also want to know how get the 'product_brand' taxonomy.

Here's my tease-product.twig:

```
{% if post.ID %}
<li class="ps-product {{post.class}}" data-product-sku="{{post.sku}}">
     {{ fn('timber_set_product', post)}}
    <figure>
        <a class="ps-img-holder" href="{{ post.link }}">
        {% if post.thumbnail %}
        <div class="product-image">
            <img class="attachment-shop_catalog" src="{{ post.thumbnail.src('shop_catalog') }}" alt="">                       
		</div>            
        {% endif %}
    	</a>
        <figcaption>
            <div class="shop-actions clearfix">
                <a href="{{post.link}}" rel="nofollow" data-product_id="{{post.ID}}" data-product_sku="{{post._sku}}" class="product_type_variable" data-added_text="Item added to bag"><i class="ss-sugarpackets"></i><span>Select options</span></a>
                <div class="yith-wcwl-add-to-wishlist">
                    <div class="yith-wcwl-add-button show"><a href="/suggestions?add_to_wishlist={{post.ID}}" data-product-id="{{post.ID}}" data-product-type="variable" class="add_to_wishlist"><i class="fa-star"></i></a></div>
                    <div class="yith-wcwl-wishlistaddedbrowse hide" style="display:none;"><span class="feedback">Product added to wishlist.</span> <a href="/wishlist/view/"><i class="fa-check"></i></a></div>
                    <div class="yith-wcwl-wishlistexistsbrowse hide" style="display:none;"><a href="wishlist/view/"><i class="fa-check"></i></a></div>
                    <div style="clear:both"></div>
                    <div class="yith-wcwl-wishlistaddresponse"></div>
                </div>
            </div>
        </figcaption>
    </figure>
    <div class="product-details">
         <h3><a href="{{post.link}}">{{post.title}}</a></h3>
        <span class="price"><span class="amount">{{ post._price|apply_filters('wc_price') }}</span></span>    
    </div>
</li>
{% endif %}

```

**Comment by tmyie** [comment] 2015-05-29 12:21
Has anyone managed to get the Cart page working?

In my theme, `/woocommerce/cart/cart.php` is used for the data. I then render a twig file. 

However, it seems to embed the twig file within the `page.twig`; resulting in two headers and two footers.

Anyone else come across this? If I use `page-cart.php` to render the data, it avoids this issue. However, it seems to remove the shipping plugin.

**Comment by rzeka** [comment] 2015-05-29 12:48
Simply don't extend base template in cart. It's a shortcode, so You will
get the base from single page's template

pt., 29.05.2015 o 14:21 użytkownik tmyie <notifications@github.com> napisał:

**Comment by tmyie** [comment] 2015-05-29 12:57
Could you elaborate? If I render the twig file from the `page-cart.php`, it seems to be lacking shipping details, etc.

**Comment by rzeka** [comment] 2015-05-29 13:11
In page-cart.php render page-cart.twig, which should extend base.twig. woocommerce/cart/cart.php is template for a shortcode in cart’s page (displayed by page-cart.php). So in woocommerce/cart/cart.php render woocommerce/cart/cart.twig but don’t extend base in there.

Hope You undertand me :)

**Comment by tmyie** [comment] 2015-05-29 13:17
Aah, thank you!

Could something similar be done with `cart-totals.php`, `cart-shipping.php`, etc?

**Comment by rzeka** [comment] 2015-05-29 13:23
I’m not sure. Just check, which pages are shortcode based :)

**Comment by joeldrapper** [comment] 2015-06-03 08:26
@jarednova is this starter theme open source? Is there anywhere we can see progress and contribute to its development?

**Comment by rzeka** [comment] 2015-06-03 12:09
https://github.com/Upstatement/timber-demo-theme <https://github.com/Upstatement/timber-demo-theme>
https://github.com/Upstatement/timber-starter-theme <https://github.com/Upstatement/timber-starter-theme>

Try there, but I’m not sure WooCommerce is included.

**Comment by tdserviceco** [comment] 2015-06-15 09:57
I got the thumbnail to work now and I did like this:
<article {{ fn('post_class','entry', post.ID ) }}>

	{{ fn('timber_set_product', post) }}

	<div class="Media">

		<div class="Media-figure {% if not post.thumbnail %}placeholder{% endif %}">
			{% if post.thumbnail.src %}
				<a href="{{ post.link }}">
					<img src="{{ post.thumbnail.src|resize(post_thumb_size[0], post_thumb_size[1]) }}"/>
				</a>
			{% else %}
				{#<span class="thumb-placeholder"><i class="icon-camera"></i></span>#}
			{% endif %}
		</div>

		<div class="Media-content">
			{% do action('woocommerce_before_shop_loop_item_title') %}
			{% if post.title %}
				<h3 class="entry-title"><a href="{{ post.link }}">{{ post.title }}</a></h3>
			{% else %}
				<h3 class="entry-title"><a href="{{ post.link }}">{{ fn('the_title') }}</a></h3>
			{% endif %}
			{% do action( 'woocommerce_after_shop_loop_item_title' ) %}
			{% do action( 'woocommerce_after_shop_loop_item' ) %}
		</div>

	</div>

</article>

**Comment by kisabelle** [comment] 2016-02-02 19:36
I'm having issues setting up Timber to work with WooCommerce. I have tried to follow the instructions here: https://github.com/jarednova/timber/wiki/WooCommerce-Integration

But when I use the timber version of woocommerce.php, nothing is being output to the WooCommerce pages because I'm getting the following fatal error:

`Fatal error: Call to a member function is_on_sale() on null in .../wp-content/plugins/woocommerce/templates/single-product/sale-flash.php on line 25`


Seems to me like the documentation has become out of date due to a recent update to WooCommerce. I prefer to let WooCommerce do it's thing and only modify it using hooks/filters for exactly this reason - I don't want to have to go through all of the changes that WooCommerce has made every time they release an update, then go poring through my theme files to see where I need to make changes so that it remains compatible... 

I would like to use Timber but following the same strategy, to load all of the WooCommerce content the "default" way through the plugin in order to avoid having WooCommerce updates breaking the site like this, so that I can safely update WooCommerce without breaking my theme. But I am not sure how to go about setting that up.

**Comment by lmartins** [comment] 2016-02-02 19:38
The page where you are getting this error is an archive or single product?
This error happens when `is_on_sale` is ran outside of a product context.

Can you share the code for PHP and Twig relevant files?

**Comment by kisabelle** [comment] 2016-02-02 19:49
@lmartins Ok I checked a bunch of different pages just to be thorough: 

The error _doesn't_ occur on the My Account page, the Cart page, the Checkout page, or the single product page. 

The error **does** occur on the following pages: Shop (/shop), and Product Archive (/product-category/my-category)

On the single product page I am also getting another issue where I'm seeing a duplicate thumbnail image.

**Comment by kisabelle** [comment] 2016-02-02 20:19
Alright, my strategy is this: using woocommerce.php with a plain PHP version of my regular page template, which in this particular theme I'm working on looks like this:

`<?php get_header(); ?>

  <div id="main">
    <div class="container page-content">
      <div class="row">

        <div class="col-md-12 main-content full-width">
          <div id="content-box">

            <?php woocommerce_content(); ?>

          </div>
        </div>

      </div>
    </div>
  </div> 

<?php get_footer(); ?>`

Note: I had to take out the following line from my template:  `<h1 class="page-title"><?php the_title(); ?></h1>` because `woocommerce_content();` also outputs the page title, which was resulting in two page titles (and my tag was also outputting the incorrect title - using the title from the first item in the shop loop)

Now the rest of my site uses Timber but the WooCommerce pages will load from the WooCommerce templates in the plugin files, they will always be up to date so I never have to worry about updating WooCommerce breaking my theme.

It would be amazing if the documentation were updated so that I would have the option to output my own templates. Currently as I stated above, it gives me a fatal error.

**Comment by lmartins** [comment] 2016-02-02 20:46
That is one way to approach. You benefit from a simpler integration, loose on Timber's flexibility to manipulate your templates.

My guess is that your loop is missing the ``{{ fn('timber_set_product', post)}}`` on each product. 
The reason for this function call is explained [here](https://github.com/jarednova/timber/wiki/WooCommerce-Integration#tease-product). 

You can use Timber and still benefit from WooCommerce updates. It does imply however that you keep the default action hooks in place, which is also demonstrated in the above example.

**Comment by hrsetyono** [comment] 2016-03-04 02:39
Hi @lmartins, I just started a WooCommerce project and met this problem too. I followed your guide and the Product Description is empty.

Of course I can remade the layout using {{ post.content }} but I want to keep the hook in case of 3rd party plugins.

I posted a message to you [here](https://github.com/jarednova/timber/issues/526). Since you closed this issue, have you found the solution for this?

Thanks

**Comment by lmartins** [comment] 2016-03-04 08:02
Let me get to my computer and I'll see if I can help  
--  
Luís Martins

**Comment by hrsetyono** [comment] 2016-03-04 09:02
Hi @lmartins 

I just set up a test environment for this issue. I will send you the details to your email (from your profile).

Thanks

**Comment by hrsetyono** [comment] 2016-03-05 07:38
@lmartins I found a solution: Go to single product twig and add this line inside your content block:

```
// single-product.twig
{% block content %}
  {{ fn('the_post') }}
  ...
{% endblock %}  
```

**Comment by lmartins** [comment] 2016-03-06 20:24
That sounds like the problem you're having is similar to what happens in loops and described here:
https://github.com/jarednova/timber/wiki/WooCommerce-Integration#tease-product

Namely the global `$product` is for some reason not associated with the right post. That could also be fixed by running the helper described in the link above, `{{ fn('timber_set_product', post)}}` it the top of your `single-product.twig`. Make sure that the post object contains your product post, you can inspect any timber variable with `{{ dump( post ) }}`.

**Comment by hrsetyono** [comment] 2016-03-07 02:54
@lmartins Thanks for the clarification. If you have the permission, maybe you can update the wiki to mention this problem. :)

**Comment by jon-childs** [comment] 2016-03-08 23:29
@lmartins On the Shop page, as per your suggestion, I `{{ dump($post) }}` in `tease-product.twig`, and it always ends up being the `TimberPost` of the archive page `/shop`.

Basically `$context['products']` is not the array of products, but just the archive page. I am using `woocommerce.php` as [provided here](https://github.com/jarednova/timber/wiki/WooCommerce-Integration#point-of-entry---main-woocommerce-php-file)   
Any thoughts or suggestions are much appreciated!

**Comment by lmartins** [comment] 2016-03-09 09:16
@jon-childs how does your `for` loop looks like?

Anyway, I think I'll build a complete starter theme for Timber and WooCommerce so that we all can improve on that. Definitely there are a few gotchas and weird edges cases but overall for anyone struggling my suggestion push forward and you wont regret to stay with Timber.

**Comment by jon-childs** [comment] 2016-03-09 16:37
@lmartins My `for` loop is the same as what @jarednova provided [here](https://github.com/jarednova/timber/wiki/WooCommerce-Integration#archives). My `archive.twig` is the same.

That would be great if you were to work on a Starter Theme. I would happily contribute.

**Comment by jon-childs** [comment] 2016-03-09 18:25
@lmartins Ok, so I think I experienced a weird edge case. If a post type of Product existed before from another plugin, things get weird. Trashing old Product posts and creating new ones seemed to right the confusion with Product archive pages, being `/shop`.

**Comment by connorjburton** [comment] 2016-04-14 18:39
Hey guys, I'm going to close this in favour of Stackoverflow and Gitter and it the thread now seems to be far removed from the original issue.

Thanks

**Closed by connorjburton** 2016-04-14 18:39 UTC
Labels: contrib-opportunity, enhancement

**Comment by sdunham** [comment] 2017-05-17 19:24
FYI, I was running into the same issue mentioned above with product thumbnails always displaying the same image as the first product post in the loop. I think I've tracked down the source of the issue.

Basically, it appears that the WooCommerce template responsible for outputting the product thumbnail is [using the global $post object, and not the global $product object](https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-image.php#L58). Which means you can address the issue by updating the `timber_set_product` function to the following:

```
function timber_set_product( $currPost ) {
    global $post, $product;
    if ( is_woocommerce() ) {
        $product = wc_get_product($currPost->ID);
	$post = get_post($currPost->ID);
    }
}
```

I'll be opening a new issue get somebody else's eyes on this, and recommend updating the docs to update the definition of `timber_set_product`, but I wanted to post here as well in case people come here looking for answers in the meantime.

**Comment by lmartins** [comment] 2017-05-17 19:37
@sdunham that is described here https://github.com/timber/timber/wiki/WooCommerce-Integration#tease-product

**Comment by sdunham** [comment] 2017-05-17 19:38
Derp, I totally missed that in the docs. Sorry!

**Comment by lmartins** [comment] 2017-05-17 19:40
No, no worries at all, I just mentioned in case you bump into any other weirdness with Woo integration.

**Comment by omikron** [comment] 2017-07-29 05:32
Is there any place to track progress on this?

**Comment by hrsetyono** [comment] 2017-08-16 01:51
Just for reference, I've made a starter theme for WooCommerce by combining all the snippets I got from above.

It's part of my Yeoman generator: https://github.com/hrsetyono/generator-edje/

You can take a peek by clicking `/templates/woocommerce`. The files there will be combined with the files from `/templates/wordpress`

**Comment by stefan0s** [comment] 2017-11-15 11:52
Hello,

Is there any example to handle cart, checkout, dashboard of woocommerce using twig files?

**Comment by hrsetyono** [comment] 2017-11-16 06:07
There's no easy way to do that since most of HTML markup in Cart and Checkout are hardcoded. You need to rewrite the whole thing which I never tried so can't guarantee it will work well either.

Just use the default markup and use CSS to patch it up.

I wrote a plugin to massively overhaul Checkout page with just CSS and little bit of JS https://github.com/hrsetyono/woocommerce-edje#2-clean-checkout-page

**Comment by stefan0s** [comment] 2017-11-16 08:24
I am trying to find the best way to develop a twig cart (and later on checkout and dashboard) and also easy update woocommerce without breaking my layout.

1) At the moment i as passing into the context the $commerce global variable
2) I have created a wordpress page cart (linked with woocommerce cart) and linked with a custom template page-cart
3) Within that custom twig template i have to render all cart items, coupons, ship methods etc.

What do you think about that approach?

**Comment by marciojc** [comment] 2017-11-16 09:57
@stefan0s you can add an action to you template `woocommerce_before_template_part` and when the template_name is 'cart/cart.php' you change it to your twig file.

**Comment by hrsetyono** [comment] 2017-11-16 14:36
@stefan0s I used to try that but I feel it's becoming too complicated since the file are scattered and nested into deep directory.

I don't think WooCommerce will do any major changes to the default HTML markup for cart and checkout since it will broke ALL woocommerce themes.

**Comment by MitchJackson94** [comment] 2017-12-04 11:42
I'm looking to change the related products template on the single product page to the same as the products archive page how can I achieve this?

**Comment by hrsetyono** [comment] 2017-12-07 03:57
@MitchJackson94 The most straightforward way is to just replace the Action to output related product with your own markup in TWIG.

If you want to keep the Action, you can try filtering it, but I'm not sure how flexible it is

**Comment by KenzaGiovanni** [comment] 2018-02-06 08:15
Hi, Is there anyway to keep Categories a different page in Twig?

Thanks!

**Comment by hrsetyono** [comment] 2018-02-08 02:56
@KenzaGiovanni this chart is always useful https://developer.wordpress.org/files/2014/10/wp-hierarchy.png

Woocommerce taxonomy is `product_cat`. So create a file named `taxonomy-product_cat.php` and inside there you can render conditionaly using `if_product_category('something')`
