### ISSUE TITLE
Timber 1.x for PHP8.2

### ISSUE THREAD

**Issue by jgsanchezg** [timber/timber#2791] opened 2023-08-14 22:16 UTC
## Is your feature request related to a problem? Please describe.
Looking forward to update my PHP to 8.2 version, however, I am getting lots of warnings by using the Timber 1.21.1 version.

## Describe the solution you’d like
Wondering if there is a change for an updated 1.X version that takes care of deprecated warnings when using PHP 8.2

## Describe alternatives you’ve considered
I tried to use the version 2.0 but we are not ready to migrate to that version yet so that I why I wonder if its an option to work on an updated and compatible with PHP 8.2 version

## Additional context
Most of the warnings I get are Deprecated warnings about the dynamic creation of properties in the timber/timber/lib/Core.php, Site.php and Integrations.php files

**Comment by rmens** [comment] 2023-08-20 21:48
The small team running Timber already requires all focus to get 2.0 out. I bet that patching 1.x is not an option.

**Comment by mattneal-stafflink** [comment] 2023-08-24 11:23
I'm new to Timber (been using Blade a lot though) and I get the same thing. I'm working on an existing theme that could benefit Timber, and I've chosen to use the plugin. Will the plugin be updated to 2.0 at the same time?

**Comment by rmens** [comment] 2023-08-24 11:26
This is what I understood from other discussions:

- There won't be any plug-in updates
- The only way forward is installing via Composer
- Timer 1.x wil not be updated to support anything newer than PHP 8.0

Plans might change, but this seems to be the current state.

**Comment by mattneal-stafflink** [comment] 2023-08-24 11:31
That's perfectly fine, I just read the instructions to install it using composer and I've already got it working without the plugin. Should have just done that first haha. Thanks @rmens !

**Comment by nlemoine** [comment] 2023-08-24 12:18
I can confirm what @rmens said above. Closing the issue since you seem to have found the way to make everything work! :)

**Closed by nlemoine** 2023-08-24 12:18 UTC

**Comment by mattneal-stafflink** [comment] 2023-08-24 22:13
@nlemoine I'm not OP, but I don't think OP has a choice but to stick with PHP 8.0 or make the leap to 2.0. So either way, case closed!
