### ISSUE TITLE
Multisite and {{site}} variable

### ISSUE THREAD

**Issue by haroldangenent** [timber/timber#568] opened 2015-06-11 11:57 UTC
On Multisite, `TimberSite::init_with_multisite()` is called, instead of `TimberSite::init()`. However, some attributes are not set or set to the wrong value. For example:

- `charset` is not set
- `language_attributes` is not set
- `language` is not set
- `url` is set to the wrong value (Site URL instead of Home URL like in single-site installs).

There are probably several other differences.

Is this by design?

**Comment by jarednova** [comment] 2015-06-15 22:58
Hi @haroldangenent, not by design -- likely by oversight (multisite was added later). Are the properties you're referring to on the main Timber `$context` object? Or ones on the `TimberSite` object?

**Comment by haroldangenent** [comment] 2015-06-16 08:49
The ones on the `TimberSite` object (so in the `$context['site']` variable). You can see the differences by looking at `TimberSite::init_with_multisite()` and `TimberSite::init()`.

**Comment by jarednova** [comment] 2015-06-18 21:11
cool, thanks @haroldangenent I'll take a look!

**Comment by jarednova** [comment] 2015-06-25 22:20
@haroldangenent -- this has a patch: PR #583. Tests are running now in Travis. If you have a chance to evaluate, I'd love your feedback before merging into master

**Comment by haroldangenent** [comment] 2015-06-26 13:10
@jarednova Seems to work great, thanks!

**Comment by haroldangenent** [comment] 2016-04-13 08:33
@jarednova While the patch worked and 0.21.4 (https://github.com/timber/timber/blob/0.21.4/lib/timber-site.php) was working as well, this seems to have been reverted in later installs.

Is this done purposefully? If so, I am now having issues again with a different `home` than `site_url` (for example, when installing WP in a separate folder).

**Comment by connorjburton** [comment] 2016-04-13 15:46
It seems to have been reverted in this commit https://github.com/timber/timber/commit/83b04f6aaf613acfd5a5ed78b96666036d173009 - will investigate

**Comment by jarednova** [comment] 2016-06-01 01:12
@connorjburton has patched this in #1028. @haroldangenent: are you able to confirm this by trying out the current `master` in your project?

**Comment by haroldangenent** [comment] 2016-06-01 15:27
@connorjburton @jarednova Thanks! Couldn't test really thorough, because most Multisite projects and starters themes are broken under 1.0 (congratulations on 1.0 by the way!), because of namespacing. 

After some superficial fixing, it does seem to work properly. I would recommend using `home_url()` over `get_bloginfo()`, since `get_bloginfo('url')` just calls `home_url()`. `home_url()` is a bit more descriptive, since it specifically shows the destinction between the home and site url.

**Comment by connorjburton** [comment] 2016-06-01 15:31
@haroldangenent Thanks for the response. What is broken by `1.0.0`? It should be backwards compatible with previous versions, unless deprecated functions were used.

**Comment by haroldangenent** [comment] 2016-06-02 09:15
@connorjburton I wrongly assumed that you broke backwards compat when implementing PSR-4 type namespacing. Dug a little deeper. Figured out that the origin of the problem was that I loaded through Packagist via autoloading (`timber/timber`), when loading via `wpackagist/timber-library` before.

This caused a fatal error, because all Composer dependencies are loaded before WP loads (Bedrock-type setup). In turn, Timber `1.0.3-` was calling `is_admin()` on initialization which caused the error. `dev-master` fixes this. However, you would need to initialize Timber yourself at the appropriate moment. Two questions about this, which I hope you want to answer:

- What is the appropriate moment to initialize Timber? Via a `mu-plugin` or when initializing a Timber-based theme?
- Are the new namespaced classes preferred over the old ones? In other words, is `new Timber\Post()` favored over `new TimberPost()`?

Sorry for getting off-topic.

**Comment by connorjburton** [comment] 2016-06-02 20:20
Gotcha.

Best place to init Timber would probably be in theme `functions.php` if you wanted your theme to init Timber. This is still in progress, see #1041 

New namespaces are preferred yes, keeps everything much cleaner, they are backwards compatible though.

**Comment by jarednova** [comment] 2016-06-24 15:09
@haroldangenent — I've merged @connorjburton's #1050 into `master`; could you let me know if that resolves the issue for you?

**Comment by haroldangenent** [comment] 2016-06-28 08:02
@jarednova Thanks. Didn't get around to respond to the PR, but yes, it resolves the issues. I was wondering about a few minor things:

- I see there's a new static method named `switch_to_blog`, but it's called from content in `Site->__construct()` like this: `$this->switch_to_blog()`. Wouldn't it be better to call it without any `$this` context: `self::switch_to_blog()`?
- Would there be any benefit / simplicity in using [`restore_current_blog`](https://codex.wordpress.org/Function_Reference/restore_current_blog), which restores the latest switch (instead of switching back)?
- There's a comment at the end of the `init_as_multisite()` method, which I think can be safely removed now: `//switch back to the before time`

**Comment by jarednova** [comment] 2016-06-28 13:12
@haroldangenent thanks for those notes! I made some updates to cover those in e8b344b25a89e48304adb92065b9e8a4dad57a72

... the only one I left out was `restore_current_blog`. Even though the functionality matches (as you note) I'm always very wary of "blackbox" functions that rely on globals to store/pass that information. There's probably low risk here; but I'd rather go a slightly more verbose route that makes it very clear what's happening. Thanks again for your help on this thread! Glad to have this sewn-up

**Closed by jarednova** 2016-06-28 13:12 UTC
Labels: confirm-and-close, has-patch, needs-investigation

**Comment by haroldangenent** [comment] 2016-06-28 14:50
I see, that makes sense. Thanks for your response and work on this!
