### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in C:\xampp\htdocs\marine\wordpress\wp-content\plugins\timber-library\lib\Twig.php on line 268

### ISSUE THREAD

**Issue by joethuoo** [timber/timber#1381] opened 2017-04-04 09:57 UTC
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

WHY DO I GET THIS? Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in C:\xampp\htdocs\marine\wordpress\wp-content\plugins\timber-library\lib\Twig.php on line 268

**Comment by jarednova** [comment] 2017-04-05 02:48
Hey @joethuoo thanks for posting, but I'm afraid I need more info in order to recreate the issue. Could you post more information so I can reproduce?

**Comment by joethuoo** [comment] 2017-04-06 16:13
I
![screenshot 1](https://cloud.githubusercontent.com/assets/3135231/24764449/0857799e-1afd-11e7-9d75-ce87ccc84548.png)
 installed Timber via installing the plugin on WordPress admin. 
The actual behavior: Everything appears as it should, because i haven't started the hooking the posts. This is just from adding my html css js and images from my designer.
I've only worked on the header and footer.
Nothing has been tinkered on from the back-end PHP files.
I am using (WordPress version 4.7.3) PHP 5.6.30 on xampp, Timber 1.2.4

**Comment by frecklebit** [comment] 2017-04-11 20:17
I'm getting the same thing.

**Comment by frecklebit** [comment] 2017-04-12 14:32
I opened the lib/Twig.php file and added an @ to suppress the warning but this is something that should be looked into.

**Comment by joethuoo** [comment] 2017-04-14 19:47
@frecklebit I had this solution from stackoverflow, but i can't tell what happened there. Further should be looked into. 
 http://stackoverflow.com/questions/43263238/warning-call-user-func-array-expects-parameter-1-to-be-a-valid-callback-timb?noredirect=1#comment73729489_43263238

**Comment by bderstine** [comment] 2018-03-08 14:29
I had the same error and googling brought me here, so I actually answered this on the stackoverflow page too, but the real issue I was running into was trying to use the fn() function to check a wordpress function, I needed to add single quotes around the name of the function. Error gone!

`{% if fn('wp_is_mobile') %}`

**Comment by gchtr** [comment] 2018-03-10 15:06
Ah, now I get.  It could very well be a function call from Twig that causes the problem. Unfortunately, sometimes the error messages that result from Twig don’t tell you where exactly the origin of the error is. But what you can do in a case like this is to

- comment out different sections of your Twig files to see when the error message disappears
- and then figure out exactly which line causes the error.

As @bderstine mentioned, it could be that Twig can’t find a function that you want to call. This could have several reasons:

- A syntax error. For example, if you use `{{ fn(myfunction) }}` instead of `{{ fn('myfunction') }}`, it won’t work.
- A function that doesn’t exist. If you call `{{ fn('myfunction') }}`, but `myfunction` is not defined as a function in PHP, then this could cause the error.

Editing a file in the Timber library is never a solution, because it would be overwritten with the next update. We can’t say that nothing’s wrong with Timber or Twig, but we would first need to be able to reproduce an error to tell what exactly causes it.

**Comment by tanmoy-web** [comment] 2020-12-29 16:21
add_action('woocommerce_after_add_to_cart_button', array( $this , 'ci_cart_text') );
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Ci_Simple_Features' does not have a method 'ci_cart_text' in C:\xampp\htdocs\theme\wp-includes\class-wp-hook.php on line 287

Please help me 

Thanks

**Comment by marciojc** [comment] 2021-01-02 19:16
@tanmoy-web it appears that the ci_cart_text function is not defined. 
`class 'Ci_Simple_Features' does not have a method 'ci_cart_text'`

**Comment by gchtr** [comment] 2023-03-08 10:36
Closing this because we still have no additional info to solve this. Please fill out a new detailed issue if this is still a problem.

**Closed by gchtr** 2023-03-08 10:36 UTC
Labels: needs-info, help wanted, 3rd-party

**Comment by nzurita** [comment] 2024-04-23 10:08
There are many of us having this issue after a PHP upgrade. I have same issue after upgrading to PHP 8.1, I have Timber 1.23.1 and get this error:

> Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "is_plugin_active" not found or invalid function name in /home/fundacmb3/public_html/fundacioneducativafranciscocoll.es/wp-content/plugins/timber-library/lib/Twig.php:296

I don't think this should be closed and Timber should provide some guide over this solution.

Thanks.

**Comment by rmens** [comment] 2024-04-23 10:36
I don’t think necroposting in a closed ticket from 2017 is the right way. PHP 8.1 wasn’t released in 2018, when the last contribution that’s not directly related to user error was made here. So the issues might not even be related. 

Creating a new ticket is probably better.

**Comment by nzurita** [comment] 2024-04-23 11:03
> I don’t think necroposting in a closed ticket from 2017 is the right way. PHP 8.1 wasn’t released in 2018, when the last contribution that’s not directly related to user error was made here. So the issues might not even be related.
> 
> Creating a new ticket is probably better.

You're right, I didn't look at the dates, sorry.
