### ISSUE TITLE
get_avatar_url() error

### ISSUE THREAD

**Issue by stevefuentes** [timber/timber#1568] opened 2017-10-03 22:54 UTC
Getting this error on my site after upgrading to Timber Version 1.5.0.
This is in the frontend, and causes the site to not work, and also in some admin areas.
Wordpress Version is 4.0.19

From PHP error log:
PHP message: PHP Fatal error:  Call to undefined function Timber\get_avatar_url() in ..../lib/User.php on line 148

**Comment by iign** [comment] 2017-10-04 14:04
For what it's worth, I'm not able to reproduce the issue using Timber 1.5.0, WP 4.8.2.

**Comment by palmiak** [comment] 2018-10-10 21:19
@stevefuentes do you still get this error? 

Like @iign I also can't reproduce the bug.

**Comment by palmiak** [comment] 2018-10-23 23:00
I'll close it for now - if someone will be able to reproduce the bug - I'll open it again.

**Closed by palmiak** 2018-10-23 23:00 UTC
