### ISSUE TITLE
Dashboard Pages search returns Posts

### ISSUE THREAD

**Issue by designbyblake** [timber/timber#1398] opened 2017-04-25 03:45 UTC
### Expected behavior
Performing a search in Pages, when logged into WordPress Admin, should return post type of pages.

### Actual behavior
Search results returns only posts which are not related to the search query. However in the URL post_type=page. Below is an example URL after a page search.

/wp-admin/edit.php?s=About&post_status=all&post_type=page&action=-1&m=0&seo_filter&paged=1&action2=-1  

Note turning off the Timber plugin fixes this issue

### Steps to reproduce behavior

1. Login to WordPress
2. Click Pages
3. Type query in search input
4. Click "Search Pages"
5. See results listing

### What version of WordPress, PHP and Timber are you using?

PHP 7.0.11
WordPress 4.7.2
Timber 1.1.8

and 

PHP 7.0.11
WordPress 4.7.4
Timber 1.2.4

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Timer was installed from Github download

**Comment by Levdbas** [comment] 2023-03-03 10:11
Cannot reproduce this behavior in the current 1.x branch.

**Comment by gchtr** [comment] 2023-03-03 10:21
Let’s close this then. If that issue should happen again, please create a new issue.

**Closed by gchtr** 2023-03-03 10:21 UTC
