### ISSUE TITLE
2.x missing timber/class/posts_iterator filter

### ISSUE THREAD

**Issue by philsbury** [timber/timber#2834] opened 2023-11-02 08:48 UTC
### Expected Behavior

In v1 we could use a custom PostIterator which was useful when working with things like Woocommerce products. We not longer seem to be able to do it. `timber/class/posts_iterator` should still allow developers to pass their own custom iterators

### Actual behavior

`timber/class/posts_iterator` is not longer functional and not mentioned in the docs as being deprecated or removed

### What version of Timber are you using?

2.0-rc-1

### What version of WordPress are you using?

6.3.x

### What version of PHP are you using?

PHP8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by Levdbas** [comment] 2023-11-03 08:16
Hi @philsbury ,

I found this message in a PR: https://github.com/timber/timber/pull/1778#issuecomment-420564281
It's said that you could now use custom posts classes / setup function for that. Let me know if that answers your question!

**Comment by gchtr** [comment] 2023-11-03 08:30
That’s a good catch, @philsbury. We definitely need to update that in the Upgrade Guide. I will prepare a note for that.

What @Levdbas says is correct.

We updated the `Timber\PostsIterator` class for better compatibility with other WordPress plugins when looping over posts. We took great care to make sure that Timber calls the right functions and WordPress hooks in the right places when looping over posts.

For this, we used [`setup()`](https://timber.github.io/docs/v2/reference/timber-post/#setup) and [`teardown()`](https://timber.github.io/docs/v2/reference/timber-post/#teardown) methods for posts. These methods can be used if you need to manipulate post objects before they are accessed in a loop.

We removed  the `timber/class/posts_iterator` filter hook, which you could use to use a custom post iterator. The functionality that you would handle with a custom post iterator can now be handled with the `setup()` and `teardown()` methods. To write custom `setup()` and `teardown()` methods, you can [extend the `Timber\Post` class](https://timber.github.io/docs/v2/guides/extending-timber/).

In your case, you would add a `Product` class for WooCommerce products and then add a custom `setup()` method.

```php
class Product extends Timber\Post {
	public function setup() {
		parent::setup();

		// Do your own thing.

		return $this;
	}
}
```

If you’ve used a custom post iterator to handle a plugin incompatibility, it might very well be that you won’t need to do anything and that the issue is resolved with the existing post iterator implementation in Timber 2.0. So before you start using custom setup and teardown methods, make sure you need it.

**Comment by gchtr** [comment] 2023-11-09 08:43
This is now live in the docs: https://timber.github.io/docs/v2/upgrade-guides/2.0/#better-compatibility-with-plugins.

**Closed as completed by gchtr** 2023-11-09 08:43 UTC
Labels: docs, has-patch, 2.0

**Comment by philsbury** [comment] 2023-11-09 14:25
Thanks both, this is super helpful and I have things (mostly) working!
