### ISSUE TITLE
ACF repeater field not working when defined in code

### ISSUE THREAD

**Issue by chrisgherbert** [timber/timber#1586] opened 2017-10-26 23:23 UTC
### Expected behavior
`post.get_field()` works for ACF repeater fields even if the the fields were defined in PHP, not in the ACF GUI.

### Actual behavior
While the fields work fine in the backend, and save their information to the database without any problem, Timber just sees the count of the number of items in the repeater field (as if it was a standard text field).

### Steps to reproduce behavior

Here's the code I'm using to define the field for ACF.  This works fine, except with Timber.

```php
		acf_add_local_field_group(array(
			'key' => 'front_slider',
			'title' => 'Home Page Slides',
			'fields' => array(
				array(
					'key' => 'slides',
					'label' => 'Home Page Slides',
					'name' => 'slides',
					'type' => 'repeater',
					'layout' => 'row', // 'row', 'table', 'block'
					'sub_fields' => array(
						array(
							'key' => 'title_text',
							'label' => 'Title Text',
							'name' => 'title_text',
							'type' => 'textarea',
							'rows' => 2
						),
						array(
							'key' => 'subtitle_text',
							'label' => 'Subtitle Text',
							'name' => 'subtitle_text',
							'type' => 'textarea',
							'rows' => 2
						),
						array(
							'key' => 'link_label',
							'label' => 'Link Label',
							'name' => 'link_label',
							'type' => 'text'
						),
						array(
							'key' => 'link_url',
							'label' => 'Link URL',
							'name' => 'link_url',
							'type' => 'text'
						),
						array(
							'key' => 'background_image',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => 'The image should be low-contrast enough to have overlaid white text be visible. For desktop users, the text will be aligned to the left, so consider making that side darker',
							'return_format' => 'id'
						)
					)
				)
			),
			'location' => array(
				array(
					array(
						'param' => 'page_template',
						'operator' => '==',
						'value' => 'page-home.php'
					)
				)
			)
		));
```
### What version of WordPress, PHP and Timber are you using?
WordPress 4.8.2, PHP 7.0.0, Timber 1.5.2

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Composer

**Comment by chrisgherbert** [comment] 2017-10-27 17:09
I have no idea why this would matter, but it started working when I changed the repeater field's key and name to something else.

**Comment by ruscon** [comment] 2017-11-07 14:43
in function.php
try to add

`new \Timber\Timber();`

**Comment by Soben** [comment] 2017-11-10 14:37
@ruscon can you clarify on that a little more? It seems a little weird to add another instance of Timber() to be running, if it's unnecessary. I think a better solution is needed.

@chrisgherbert what was the key/name before and after, if you still have access to that.

I have noticed weird quirks with ACF in terms of situations where two keys matched (especially when you're handling the code via PHP, because otherwise ACF is good about making the key unique)... this could help narrow down why that solved your problem.

**Comment by christohill** [comment] 2017-11-15 08:44
I'm getting this issue as well and it's got me stumped. Neither of the options above fixed the issue for me either. ACF group is similar to @chrisgherbert but when I loop through the sub fields:

```
{% for item in post.get_field('formats') %}
	{{ item | print_r }}
{% endfor %}
```
Returns:
`Array ( [] => 1 ) Array ( [] => 1 )`

Which is strange because it's looping the right amount of times, but they're empty.

Same code tested on a repeater created through the UI returns the data properly.

**Comment by chrisgherbert** [comment] 2017-11-18 02:40
@Soben Sorry, I don't remember. I think the issue was that I'd previously had a non-ACF custom field with the same key.  I'm not sure why that should have made a difference (there wasn't any other post meta under that key for the post), but it seemed to.

**Comment by Soben** [comment] 2017-11-18 14:20
@chrisgherbert That would make a difference because ACF is weird, lol. They prefer you to request it by it's key and not the slug.

Say for instance you have an ACF field that has the slug `name` and key `field_666` ... if you have more than one meta field (ACF or no) using `name`, get_field(`name`) is unreliable, because ACF may grab the wrong field in the meta. This is especially true if you're calling for an ACF field that is list/repeater/gallery, etc.

I have found instances where I ended up calling it by the key `field_666` instead of the slug, to ensure reliability. My problem with using the key is readability in my code. I end up defining constants to get around that.

That said, @christohill introduced an interesting test, that I am going to try to replicate myself. I'm curious about this whole thread because we use ACF heavily, and we're starting to integrate Timber into our base default theme, so this may be something I contribute to resolving.

**Comment by gchtr** [comment] 2017-11-18 15:35
Just to clarify: there have been quite a few issues with repeater fields (like https://github.com/timber/timber/issues/1351), which a lot of times boil down to the problem that Timber wasn’t initialized in functions.php `new \Timber\Timber();`.
That’s why when you have an issue with repeater or flexible content fields in ACF, it’s usually what people ask you first. Certainly `new \Timber\Timber();` doesn’t have to be called twice.

However, to me it seems like this is a different issue, which I’ve experienced once myself, not with a repeater field, but with a file field. The field wasn’t working when it was named `print_pdf`. When I renamed it to `printpdf`, it worked again. Unfortunately I didn’t find out what the issue was. To me it seems like `print_pdf` is a totally non-generic name, so it seems unlikely that something else was named the same.  
I just tried to reproduce the error in that project, no luck.

**Comment by christohill** [comment] 2017-11-18 18:28
@Soben I was able to work around the problem by adding my repeater fields directly to the group array.

Initially I was using ``acf_add_local_field_group()`` and then adding fields to it using ``acf_add_local_field()`` and referencing the id of the group. This was giving the results I saw above.

Switching to using this fixed my issue: 

    acf_add_local_field_group(array(
        'key' => 'test_key',
        'fields' => array(ADD_FIELDS_HERE)
    ));

I still find it strange that using ``acf_add_local_field()`` was looping the right amount of times, but never returning any data, and that it worked when adding the same group/fields through the UI.

@gchtr I also tried very unique field names/id's and had no luck with the problem, so I think you're right there.

**Closed** 2023-03-06 08:53 UTC
