### ISSUE TITLE
Conflict with latest version of Stripe and Timber

### ISSUE THREAD

**Issue by Adele2000** [timber/timber#2942] opened 2024-03-05 12:55 UTC
When my WooCommerce Stripe Gateway plugin
was updated (version 8.0.0) my checkout had bugs: the credit card payment form no longer appeared.
By changing the theme the problem disappeared, so I reverted to an older version of Stripe and it started working again. So there is a conflict between Stripe and Timber, how can I resolve it to update?

**Comment by Levdbas** [comment] 2024-03-05 14:11
Hi @Adele2000 ,

Please do not bypass our bug template. We now have no idea what version you run of Timber and thus cannot help you. And please try to debug this issue first yourself. Did you check if all the scripts are loaded when updating to 8.0 of Stripe?

**Comment by Adele2000** [comment] 2024-03-05 14:12
I installed Timberx2 with composer

**Comment by Levdbas** [comment] 2024-03-05 14:21
And prior to the Stripe 8.0 update, Timber 2.0 was also already installed? If so, this must be something caused by the theme running Timber that doesnt play well with the latest version of Stripe. You could try adding this:

> > To chime in on this:
> > Since I added the following snippets in my timber projects, I never ran into compatibility issues again. The do action hooks fixed some compat issues with the Rank Math SEO plugin for example.
> > ```
> > {# head.twig in the <head> #}
> > {% do action('get_header') %}
> > {{ function('wp_head') }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > {# base.twig just before the closing body tag. #}
> > {% do action('get_footer') %}
> > {{ function('wp_footer') }}
> > ```
> 
This solved a lot of compat issues with plugins running my own projects

**Comment by Adele2000** [comment] 2024-03-05 14:27
Yes before the Stripe update, Timber 2.0 was already installed, I'm going to try the hook!

**Comment by Adele2000** [comment] 2024-03-05 14:31
like this?

<head>

    {% do action('get_header') %}
    {{function('wp_head')}}

**Comment by Adele2000** [comment] 2024-03-05 14:35
no it doesn't work

**Comment by Adele2000** [comment] 2024-03-05 15:39
I have the same problem with the latest version of WooPayment and when I change the theme to Storefront for example, it works perfectly. So it must come from Timber, do you know what it could be and how to fix it?

**Comment by Levdbas** [comment] 2024-03-05 17:10
Sorry, but we do not provide support on a project basis. There must be something missing in the theme which is required by the latest versions of said plugins. Nothing in Timber that comes to mind that could cause this issue on its own.

I advice you to check your loaded scripts when Storefront is active and compare that to your timber theme. Check if there are scripts missing then. That would point you in the right direction.

**Comment by rmens** [comment] 2024-03-05 20:19
> I have the same problem with the latest version of WooPayment and when I change the theme to Storefront for example, it works perfectly. So it must come from Timber, do you know what it could be and how to fix it?

First enable debug mode in WP, look in your browser console for javascript errors and check the PHP error logs of your website.

You can't just open an issue and do _zero_ investigation yourself. Switching a theme and concluding "This one is not made with Timber so that must be it!" is not enough. I'm sure you can do better, even if you're a coding bootcamper.

**Comment by Adele2000** [comment] 2024-03-05 20:36
Yes I investigated to understand, there are no javascript or php
errors, and it works with all the other themes. But I'll keep looking,
thanks.


Le mar. 5 mars 2024 à 21:20, Raymon Mens ***@***.***> a
écrit :

**Comment by Levdbas** [comment] 2024-03-13 15:12
Did you manage to fix this issue @Adele2000?

**Comment by Adele2000** [comment] 2024-03-14 16:33
Hello, No I haven't found it yet. For the moment I use the wooPyment
plugin with the Stripe plugin (old version). If I disconnect Stripe or
update the version, WooPayment no longer works


Le mer. 13 mars 2024 à 16:12, Erik van der Bas ***@***.***> a
écrit :

**Comment by Levdbas** [comment] 2024-03-14 20:08
Can you give me the exact version number of Woopayments where the problem occurs for the first time and the last version it still works on? I can take a look at the changelogs of Woopayments to maybe find out what casues this issue. 

And If you can post your twig wrapper, head and footer file please. That would help.

**Comment by Adele2000** [comment] 2024-03-15 14:22
Hello, thank you for your message. The problem is that I can't use
WooPayment without activating the Stripe plugin (which is not normal), so I
have both plugins activated for it to work. However, it was during the
Stripe update that the bug appeared (version 8.0.1). The latest version
used and working is: 7.9.3

header :
<head>
    <meta charset="{{ site.charset }}" />
    <meta name="description" content="{{ site.description }}">
    <link rel="stylesheet" href="
***@***.***/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ site.theme.link }}/styles/main.css" type
="text/css" media="screen" />
    <link rel="preload" as="font" type="font/woff" crossorigin="anonymous"
href="/wp-content/themes/timber-library/Adele/fonts/Söhne-Kräftig.woff">
    <link rel="preload" as="font" type="font/woff" crossorigin="anonymous"
href="/wp-content/themes/timber-library/Adele/fonts/Söhne-Extraleicht.woff"
>
    <link rel="preload" as="font" type="font/woff" crossorigin="anonymous"
href="/wp-content/themes/timber-library/Adele/fonts/Söhne-Leicht.woff">
    <link rel="preload" as="font" type="font/woff" crossorigin="anonymous"
href=
"/wp-content/themes/timber-library/Adele/fonts/Söhne-LeichtKursiv.woff">
    <link rel="preload" as="font" type="font/woff" crossorigin="anonymous"
href="/wp-content/themes/timber-library/Adele/fonts/Söhne-Leicht.woff">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="author" href="{{ site.theme.link }}/humans.txt" />
    <link rel="pingback" href="{{ site.pingback_url }}" />
    <link rel="profile" href="http://gmpg.org/xfn/11">

    {{function('wp_head')}}



footer : <footer id="footer">
{% include 'footer.twig' %}

{% if function('has_nav_menu', 'footer_menu') %}
<nav>
{% if fn('is_front_page') %} {% else%} {{ function('wp_nav_menu',
{'theme_location': 'footer_menu'}) }} {% endif %}
</nav>
{% endif %}

{{ function('wp_footer') }}

</footer>

Thank you!


Le jeu. 14 mars 2024 à 21:09, Erik van der Bas ***@***.***> a
écrit :

**Comment by Levdbas** [comment] 2024-03-15 15:32
![image](https://github.com/timber/timber/assets/17764157/181995fa-8644-4607-b60c-2aaa032dc1db)

I went thought the [changelog ](https://github.com/woocommerce/woocommerce-gateway-stripe/compare/7.9.3...8.0.1#diff-9356f87eb3d1b3fbc63a5201e8ccc38668d392af16d66e94656a3ee8e101820eL157) of the Stripe gateway and found that the enqueue action has been changed. 

Can you check, when you are on version 8.0.1 of the plugin that `https://js.stripe.com/v3/` and `/build/upe_classic.js` are loaded? You can check this by searching the source for those two links. I also recommend placing the `{{ function('wp_footer') }}` underneath the `</footer>` closing tag.

**Comment by Adele2000** [comment] 2024-03-19 10:39
Hello,
 I just checked, the two files mentioned are loaded on Stripe 8.0.1.
And I put the {{ function('wp_footer') }} back under the closing footer tag.
Thank you very much

Le ven. 15 mars 2024 à 16:33, Erik van der Bas ***@***.***> a
écrit :

**Comment by Levdbas** [comment] 2024-03-19 10:58
Hi @Adele2000 , we cannot help you past this point. I am 100% sure that it has something to do with script being loaded in a wrong order or some other thing in your theme that goes wrong. Unfortunately that is not something we can support. We expect Timber users to debug these issues themselves and if you are 100% sure that it is caused by Timber we want to know how to recreate the issue. 

Please create a minimal example repository with your theme code (brought back to a minimum) that we can check out. You can then create a new issue where we then can take a look at.

I am really sorry  and I hope you are able to fix this issue for yourself.

**Closed as not planned by Levdbas** 2024-03-19 10:58 UTC
Labels: question
