### ISSUE TITLE
Warning: is_a() expects exactly 2 parameters, 3 given in /var/www/..../wp-content/plugins/timber-library/lib/PostGetter.php on line 121

### ISSUE THREAD

**Issue by twentyfortysix** [timber/timber#1172] opened 2016-08-24 14:55 UTC
### Expected behavior

see no error ;)
### Actual behavior

Warning: is_a() expects exactly 2 parameters, 3 given in /var/www/..../wp-content/plugins/timber-library/lib/PostGetter.php on line 121

the error shows up only on the hosting, not on local, so I think it has something to do with PHP version.
### Steps to reproduce behavior

term.get_posts();
### What version of WordPress, PHP and Timber are you using?

WordPress 4.6, PHP Version 5.3.3-7+squeeze29, Timber Version 1.1.3

**Comment by jarednova** [comment] 2016-08-25 22:06
Indeed, according to the docs that third parameter was added in 5.3.9:

http://php.net/manual/en/function.is-a.php

... I'll look at using `instanceof` which seems to be the preferred method

**Comment by feshin** [comment] 2016-10-28 16:55
Not sure whether this is the best way to give feedback, but I can confirm that this fix seems to work for me. 

php version: 5.3.3
wordpress version: 4.5.3
timber version: 1.1.8 (with fix noted above)

**Comment by twentyfortysix** [comment] 2016-10-29 17:40
Confirmed , the fix fixes the problem.

**Comment by gchtr** [comment] 2017-07-23 08:18
Closing this, because it looks like this is fixed.

**Closed by gchtr** 2017-07-23 08:18 UTC
