### ISSUE TITLE
Blog marked as active for other content type's archives

### ISSUE THREAD

**Issue by lmartins** [timber/timber#1537] opened 2017-08-28 16:00 UTC
Is this a support or usage question? Please post to [StackOverflow](http://stackoverflow.com/questions/tagged/timber) using the Timber tag

### Expected behavior
I'm working on a site where we have several custom post types, each one with its own archive template. In each template we have a structure not too far apart from what is seen on Timber's starter theme:
https://github.com/timber/starter-theme/blob/master/archive.php

That is, we have a `get_context` at the top and further down the page we have a call to `get_posts`. 

One thing I've noticed is that even before I run the `get_posts`, the context already has a posts entry loaded. In this scenario, isn't calling `get_posts` redundant here?

Another issue I'm seeing, and perhaps this is related to the fact that `get_context` loads posts before any further logic is run on the template, is that the blog archive menu entry is marked as active for other content types.

Problem can be seen here:
https://contenderbicycles.com/our-people/

This URL loads an archive page for a custom post type and the logic looks like this:

```php
<?php

if( !defined( 'ABSPATH' ) ) exit;

use Lumberjack\PostTypes\Staff;

$context = Timber::get_context();

$templates = array('index.twig');

$queried_object = get_queried_object();
$context['taxonomy'] = $queried_object;
$context['posts'] = Staff::all();
$context['title'] = $queried_object->name;

array_unshift( $templates, get_post_type() . '/archive.twig', 'archive.twig' );

Timber::render($templates, $context);
```
If you notice on the footer menu, you'll see that both the "Blog" and "Our People" menu entries are being marked as active, even though the latter is the correct one.

Is this a bug, or how can one get around the issue above?

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org running latest version

**Comment by marciojc** [comment] 2017-09-30 14:27
Hey, our people page isn't children of the blog?

**Comment by lmartins** [comment] 2017-10-02 21:23
No. That would actually possible since the Blog is a custom archive page, but that isn't the case. I've been seeing this issue very frequently for different sites so I was wondering if anyone else seeing it.

**Comment by marciojc** [comment] 2017-10-02 22:27
Its strange because blog have `current_page_parent` class.

**Comment by lmartins** [comment] 2017-10-03 20:58
That is the issue im reporting here.

**Comment by hacknug** [comment] 2018-11-23 16:13
Experiencing the same issue :'(

**Comment by Levdbas** [comment] 2023-05-12 08:13
Closing this for now as part as a cleanup. If you still run into this issue, please open a new ticket with steps how to reproduce. Preferably without Lumberjack to keep it as close to Timber core as possible.

**Closed by Levdbas** 2023-05-12 08:13 UTC
