### ISSUE TITLE
[bug] - Timber (or Twig?) generates duplicate entries for "function wp_nonce_field"

### ISSUE THREAD

**Issue by 7php** [timber/timber#1654] opened 2018-02-06 13:16 UTC
Is this a support or usage question? Please post to [StackOverflow]
- **Support**
### Expected behavior
Should generate the following:
```
<div>
    <input type="hidden" id="name_wpnonce" name="name_wpnonce" value="a81d292134" />
    <input type="hidden" name="_wp_http_referer" value="/product-category/custompage/" />
</div>
```
### Actual behavior
But the following duplicate entries are being generated:

```
<div>
    <input type="hidden" id="name_wpnonce" name="name_wpnonce" value="a81d292134" />
    <input type="hidden" name="_wp_http_referer" value="/product-category/custompage/" />
    <input type="hidden" id="name_wpnonce" name="name_wpnonce" value="a81d292134" />
    <input type="hidden" name="_wp_http_referer" value="/product-category/custompage/" />
</div>
```

### Steps to reproduce behavior
- Create a simple twig file as follows:
**custompage.twig**
```
<div>
{{ function('wp_nonce_field', 'action_wpnonce', 'name_wpnonce') }}
</div>
```
- In PHP code call:

```
$timber = \Timber\Timber::get_context();
\Timber\Timber::render('twig/custompage.twig', $timber);
```

### What version of WordPress, PHP and Timber are you using?
- WordPress 4.9.3
- PHP 7.0.x
- Timber 1.6.0

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
- Via composer install

**Comment by gchtr** [comment] 2018-02-06 13:23
Hey @7php 

Thanks for providing an issue with all the details to reproduce the behavior!

I think the issue is not something that has to do with Timber itself, but more with how some WordPress functions work in combination with how Twig works.

The [wp_nonce_field](https://codex.wordpress.org/Function_Reference/wp_nonce_field) function has a fourth parameter `$echo`, that is `true` by default. When you call the function through Twig, `wp_nonce_field()` will echo the result **and return the result** , which is then echoed by Twig through `{{ }}` again.

You have two ways to solve this:

**Use the `$echo` parameter**

```twig
{{ function('wp_nonce_field', 'action_wpnonce', 'name_wpnonce', false) }}
```

**Call the function without echoing the result**

In Twig, using `{% do … %}` will simply execute code. In your case: the `wp_nonce_field()` function.

```twig
{% do function('wp_nonce_field', 'action_wpnonce', 'name_wpnonce') %}
```

**Comment by 7php** [comment] 2018-02-06 14:31
@gchtr thank you very much for being so quick & responsive, you are awesome.

Thank you for the very nice explanation and it makes sense.
In addition to the two solutions you mention, I am using this one below:

1) In TWIG file, do:
```
<div>
{{ _wpnounce_ }}
</div>
```

2) In PHP code, do the method call there:
```
$timber = \Timber\Timber::get_context();
$timber = [
    '_wpnounce_'  => wp_nonce_field('action_wpnonce', 'name_wpnonce')
];
\Timber\Timber::render('twig/custompage.twig', $timber);
```

Once again thank you very as the `{% do … %}` is very good to know so that I can use it in other methods or even this one.

Have a good remaining day.

Humbly,
7php
(Khayrattee)

**Comment by gchtr** [comment] 2018-02-06 14:39
Yeah, of course adding the nonce to the context is another method you could use! But again, I’d make sure the `$echo` parameter is set to false:

```php
 '_wpnounce_'  => wp_nonce_field( 'action_wpnonce', 'name_wpnonce', true, false )
```

Otherwise, you might have unwanted output at the very beginning of your HTML.

And I see that you’re overwriting the context right away with a new array. If you want to keep the context you get through `Timber\Timber::get_context()`, then you should add your custom variables *selectively*:

```php
$timber = \Timber\Timber::get_context();
$timber[ '_wpnounce_' ]  => wp_nonce_field( 'action_wpnonce', 'name_wpnonce', true, false );
```

**Comment by 7php** [comment] 2018-02-06 15:22
##### 1. I’d make sure the $echo parameter is set to false:

- yes good point

##### 2. Otherwise, you might have unwanted output at the very beginning of your HTML.

Probably not as the output is buffered with wordpress I think? But yes, let's do #DefensiveProgramming ;)

##### 3. I see that you’re overwriting the context right away with a new array

@gchtr dude thank you so much. I inadvertently made a mistake in usage there. You saved me from debugging stuffs ahead. Once again, you ARE amazing!!

&nbsp;&nbsp;

PS: I have just started using TimberWP since like 8hrs in all. So far so good and I'm definitely keeping it in my workflow with wordpress, specially when I do custom forms & handling..

Cheers mate & thanks for all you do!

**Comment by gchtr** [comment] 2018-02-06 17:04
Thanks for your very kind words ☺️! When I started with Timber a couple of years ago I ran into your problem myself. And I had the same questions that a lot of people have when asking for support. So now I try to give back what I know and save others the trouble.

> Probably not as the output is buffered with wordpress I think? But yes, let's do #DefensiveProgramming ;)

No, not really. When you call that function without the `$echo` set to `false`, it will output the hidden input fields at the current execution point. Because these are hidden fields, you’ll only see them if you inspect your page.

There’s not so much magic behind Timber as one might think, it normally only uses functions that don’t echo stuff. And when there is echoed output, then Timber buffers it with [`Timber\Helper\ob_function`](https://timber.github.io/docs/reference/timber-helper/#ob-function), which you could use as well. This is actually (although it’s rather advanced) the 4th method to solve your issue 😉:

```php
$timber[ '_wpnonce_' ] = Timber\Helper::ob_function(
	'wp_nonce_field',
	array( 'action_wpnonce', 'name_wpnonce' )
);
```

I’m going to close this, as your issue seems to be resolved.

**Closed by gchtr** 2018-02-06 17:04 UTC

**Comment by 7php** [comment] 2018-02-07 07:37
Hey @gchtr thank you once for the awesome explanations. Dude you are so helpful - that's world class support if you ask me. And that too freely for opensource - people need to be taking you a good example.

Very good for me to know about the `Timber\Helper::ob_function` - can always be helpful to situations ahead.

One personal question:
I would like to do an email-based interview with you about wordpress & your contributions..etc which I will post on my blog. If you are OK with that, can I reach you via your github profile's email?
