### ISSUE TITLE
post_content is incorrect in shortcodes

### ISSUE THREAD

**Issue by tomasvanrijsse** [timber/timber#1233] opened 2016-11-08 14:54 UTC
### Expected behavior
In a lot of shortcodes we use Timber::get_posts() with a list of id's.
The returned posts should contain their own content

### Actual behavior

They all got the post_content form the current page.
Other fields do seem fine like slug, title and id.

### Steps to reproduce behavior

```
class LatestNews
{
    static function shortcode($atts)
    {
        $atts = shortcode_atts([
            'category' => false,
        ], $atts, 'latest_news');

        $category_ids = explode(',', $atts['category']);

        $args = [
            'numberposts' => 3,
            'post_type'   => 'post',
            'post_status' => 'publish',
            'cat'         => $category_ids
        ];

        $posts = \Timber::get_posts($args);
        
        $data = [
            'posts'    => $posts
        ];

        $html = \Timber::compile('/latest_news.twig', $data);

        return $html;
    }

    static function init()
    {
        add_shortcode('latest_news', [static::class, 'shortcode']);
    }
}
```

### What version of WordPress, PHP and Timber are you using?
WordPress 4.6.1, PHP 7.0, Timber 1.1.8

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
At first it was installed with Composer/WPackagist
And I reinstalled the plugin again with the via plugin installer in WordPress admin

**Comment by jarednova** [comment] 2016-11-15 15:39
@tomasvanrijsse — I _think_ what you might be looking for is to use `{{ post.content }}` instead of `{{ post.post_content }}` the diff?

## post.post_content (and post.post_title, etc.):
These use the values exactly as stored in the WP database

## post.content (and post.title, etc.)
These use the values after they've been filtered by shortcodes and other WP filters — these are generally more appropriate for usage in a twig template

**Comment by tomasvanrijsse** [comment] 2016-11-15 15:49
We where using `post.get_preview(40,false,false,false)` in the twig file
It looks like the old school errors we used to have back in the day when we where using WP_Query in the loop with the_post(); 
And we definitely didn't use the_post :)

**Comment by palmiak** [comment] 2018-10-16 21:54
Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by DarioSwain** [comment] 2018-10-22 21:09
Hi @palmiak, I can confirm that the issue is still present. I've reproduced it right now when I've called get_posts in the shortcode callback:
```
$posts = \Timber\Timber::get_posts([
   'post_type' => 'my_custom_post_type',
   ...
]);
```

In the returned array of posts content is populated from the post in which current shortcode was injected instead of 'my_custom_post_type'. In my case it leads to infinite recursion.

**Comment by palmiak** [comment] 2018-10-22 22:57
First of all I replicated your code and it worked (there will be a small 'but' at the end):
```php
function button_shortcode() {
    $vars['posts'] = \Timber\Timber::get_posts([
        'post_type' => 'post',
        'posts_per_page' => 3,
    ]);

    $ret = Timber::compile( 'views/templates/shortcode.twig', $vars );
    return $ret;
}

add_shortcode('button', 'button_shortcode'); 
```

and the `shortcode.twig` file:
```twig
{% for post in posts %}
<h1>{{ post.title }}</h1>
{{ post.link }}
{% endfor %}
```

This works until you'll add `post.content`. But the same bug will appear in pure WP:
```php
function button_shortcode() {
    $args = [
		'post_type' => 'post',
		'posts_per_page' => 3,
	];
	
	$new_posts = new WP_Query( $args );
	ob_start();
	while( $new_posts->have_posts() ): $new_posts->the_post();
		global $more;
		$more = 1;
		the_content();
	endwhile;
	
	$output = ob_get_contents();
	ob_end_clean();
    return $output;
}

add_shortcode('button', 'button_shortcode'); 
```

It happens because you're trying to launch `do_shortcode` inside `do_shortcode` inside etc ;)

To fix this you have to:
```php
function button_shortcode() {
    $vars['posts'] = \Timber\Timber::get_posts([
        'post_type' => 'post',
        'posts_per_page' => 3,
    ]);
    remove_filter( 'the_content', 'do_shortcode', 11 );
    $ret = Timber::compile( 'views/templates/shortcode.twig', $vars );
    add_filter( 'the_content', 'do_shortcode', 11 );

    return $ret;
}

add_shortcode('button', 'button_shortcode'); 
```

**Comment by palmiak** [comment] 2018-10-29 21:43
@DarioSwain did my solution solved your problem?

**Closed** 2018-11-20 09:42 UTC
Labels: old-issue, question
