### ISSUE TITLE
Timber 1.10.0 has a breaking change

### ISSUE THREAD

**Issue by joelambert** [timber/timber#2024] opened 2019-06-12 16:22 UTC
Version `1.10.0` on Packagist includes this commit:

https://github.com/timber/timber/commit/111c70334113e3e1f6ea2121bd636a25ae93618c

This contains a breaking change to the constructor of the `MenuItem` class.

We noticed it as it causes an issue with [Lumberjack](https://lumberjack.rareloop.com) but will also break for anyone else using a custom subclass on the `MenuItem`.

**Comment by jarednova** [comment] 2019-06-12 16:25
Thanks so much @joelambert — I'll investigate a patch asap

**Comment by palmiak** [comment] 2019-06-12 16:31
This may also be the cause of menu error in other issue. I'm on mobile so
it's harder for me to check the issue ID but it has my latest response

śr., 12 cze 2019, 18:25 użytkownik Jared Novack <notifications@github.com>
napisał:

**Comment by jarednova** [comment] 2019-06-12 16:33
@palmiak I think it's #1988 ? Thanks that's helpful to know these are connected

**Comment by palmiak** [comment] 2019-06-12 16:41
I think. https://github.com/timber/timber/issues/1988#issuecomment-500921820
strange error with menu after update. Looks similar.

śr., 12 cze 2019, 18:33 użytkownik Jared Novack <notifications@github.com>
napisał:

**Comment by jarednova** [comment] 2019-06-17 00:51
This is closed by #2025. However, I don't believe that #1988 is actually connected to this issue (since that reports the issue began in 1.9.4, not 1.10.0)

**Closed by jarednova** 2019-06-17 00:51 UTC

**Comment by joelambert** [comment] 2019-06-17 06:00
Thanks for fixing this so quickly!

**Comment by jarednova** [comment] 2019-06-17 12:04
you bet!
