### ISSUE TITLE
current_item_ancestor and current_item_parent don't work, when pages have parents!

### ISSUE THREAD

**Issue by dwfee** [timber/timber#1761] opened 2018-07-26 10:26 UTC
when a page has the default parent settings , everything works fine. When another page is set as parent, current_item_ancestor and current_item_parent don't work. This is a pitty since when you have lots of pages it's nice to stack them in the intended order.

**Comment by acobster** [comment] 2018-07-28 17:48
@dwfee Could you be a little more specific about what your setup is, and what you mean when you say they don't work? Some code samples would be helpful, along with the expected behavior vs actual behavior. Thanks.

**Comment by pascalknecht** [comment] 2018-10-16 10:13
@dwfee Do you have any further informations on this? Otherwise we will close this issue as we don't have enough informations to further dig into this.

**Comment by dwfee** [comment] 2018-10-23 09:14
By they don't work I mean relevant classes are not rendered! Therefore you cannot mark parent menu items as active.

**Comment by acobster** [comment] 2018-10-23 15:57
@dfwee when you say "pages have parents," do you mean the page itself has a parent page, which you expect to be rendered with a specific class? The `current_item_*` methods traverse the *menu item* hierarchy, not the page hierarchy. If you're expecting a page that happens to be another page's parent or ancestor to be rendered in a menu with a parent/ancestor class, it will not work as expected because that it not what it is designed to do. This may be where the disconnect is.

If, on the other hand, you are parsing a menu item hierarchy and it's still not working as expected, please provide some example code and detailed context about your setup. Without that, we won't be able to reproduce or fix this issue. Thanks.

**Comment by Levdbas** [comment] 2023-05-12 08:10
Closing this as stale.

**Closed by Levdbas** 2023-05-12 08:10 UTC
