### ISSUE TITLE
Problem with images resize and retina quality.

### ISSUE THREAD

**Issue by esiao** [timber/timber#635] opened 2015-08-05 15:29 UTC
Hello I have a problem with the retina images generation.

http://i.imgur.com/9wjNSSx.png
In the attached screen you can see : 
image resized non - retina.
image resized - retina.
image resize *2.

http://i.imgur.com/yRs1lpc.jpg
The retina quality is worst than the non retina one, and the image resize *2 quality is clean.
If you take a look at the actual images you can see that the retina one has a low quality aspect. I suspect that the image is retinazed after the resize function. Meaning that it's an upscale of the non-retina one.
The *2 resize takes the base image and resize it to twice the base resize values.

I think that the attend behavior would be the *2 resize one when using retina. (with the file renaming and @2x)
Let me know your thoughts, is it working as intended or a bug ?

**Comment by kmbt** [comment] 2017-02-13 13:49
Hi, this seems to be a duplicate of #404.

**Comment by jarednova** [comment] 2017-02-13 20:34
@kmbt thanks for pointing that out — let's merge this into #404 so that things can be followed-up on there

**Closed by jarednova** 2017-02-13 20:34 UTC
Labels: needs-investigation
