### ISSUE TITLE
Timber and Gutenberg: asking for future plans

### ISSUE THREAD

**Issue by gorgoglionemeister** [timber/timber#1645] opened 2018-01-26 21:59 UTC
Is there a Timber compatibility plan with the new Gutenberg editor? Each Gutenberg block generates HTML both in the backend and in the frontend. In short, lot of HTML that can not be edited (or only partially) and that you get as is. How can Timber work in this context?

**Comment by palmiak** [comment] 2018-01-27 02:26
I think there shouldn't be any problem with Timber. `post.content` will work just the way it works now.

On the other hand - blocks can be rendered with PHP or JS. The JS part doesn't concern us. 

The PHP part looks just like in this example https://github.com/WordPress/gutenberg/blob/master/docs/blocks-dynamic.md and here timber would be very usefull. And I think it will work - I'll try to provide you with working example in a couple of days.

**Comment by gorgoglionemeister** [comment] 2018-01-27 09:13
Great! Thank you. Do you think it will be easier to extend pre-existing blocks or write new ones with Timber? I also think that the HTML rendered with JS must be the same as that rendered with PHP, for consistency.

**Comment by palmiak** [comment] 2018-01-29 13:33
After some playing around I see that there is a problem with php rendering - I mean it works but you can't pass the block attributes as seperate variables (you can pass only block options).

We'll have to wait for this as It looks they are working on it. When pass variables will be working you will be able to make block parts in timber.

On the other hand the JS part doesn't look so bad as I thought it will be (I'm not a fan of JS). I made some basic editable blocks and they worked. I'm trying to rebuild my blog's content (which is now built on ACF flexible content) to Gutenberg.

Also - everything is changing very fast so all the missing things can appear in the next update.

**Comment by gorgoglionemeister** [comment] 2018-01-29 14:26
OK, please can you share what you will do when it is ready?

**Comment by addedlovely** [comment] 2018-03-07 17:47
Great, thanks for checking it out. Adding my comment here for future notifications :)

**Comment by IngoVals** [comment] 2018-06-14 14:38
[Found this on twitter](https://twitter.com/Maximebj/status/960203611950276609)

**Comment by DrecDroid** [comment] 2018-07-18 07:54
Hi, today trying to replace content `img`s with `amp-img` I discovered gutenberg. As a Timber lover I've been trying how to mix Timber and Gutenberg, and that tweet resolved all my questions.

Basically, you have two ways of rendering gutenberg blocks, statically and dynamically.

With the static rendering you render the same way in the editor and the frontend, so you only can use javascript for the rendering, this makes the things a bit complicated because you have to go back and forth from json to html. 

With the dinamic rendering you render differently for the editor and the frontend, you don't have to have in sync the html with the json. And you now you could render your block in the frontend with Timber.

```javascript
const el = wp.element.createElement
const { 
    registerBlockType,
} = wp.blocks;

const {
    MediaPlaceholder
} = wp.editor

registerBlockType( 'superlist/amp-image', {
    title: 'AMP Image',

    icon: 'format-image',

    category: 'layout',

    attributes: {
        imageId: {
            type : 'number'
        }
    },

    edit: (props) => {
        const {
            attributes,
            setAttributes,
            className,
        } = props;
        console.log(attributes)
        function onImageSelect(imageObject) {
            setAttributes({
                imageId: imageObject.id
            })
        }

        return el(MediaPlaceholder, {
            type : 'image',
            labels: {},
            value: {
                id : attributes.imageId
            },
            onSelect : onImageSelect,
        })
    },

    save: () => null,
} );
```

This is a basic uploader that uses builtin components from Gutenberg to upload an image.
Notice that the `save` property returns `null`, this tells gutenberg that this is a dynamically rendered block.

Now the PHP code:

```php
// Superlist AMP Image Block
add_action( 'enqueue_block_editor_assets', function () {
	wp_enqueue_script(
		'superlist/amp-image',
		get_stylesheet_directory_uri().'/gutenberg/superlist-amp-image.js',
		[ 'wp-blocks', 'wp-element' ]
	);
});

add_action( 'init', function () {
	function amp_image_render( $attributes ) {
		$image = new TimberImage($attributes['imageId']);
		$output = Timber::compile('blocks/amp-image.twig', [
			'image' => $image
		]);
		
		return $output;
	}
	
	register_block_type( 'superlist/amp-image', [
		'render_callback' => 'amp_image_render',
	]);
});
```
The first part enqueues the previous script for the editor.
The second part is the replacement for the `save` property in the javascript code. It receives the same attributes that the javascript handled. This PHP code tells Gutenberg how to render the block.

The `block/amp-image.twig` file located in the Timber template folder.
```twig
<amp-img width="{{image.width}}" height="{{image.height}}" layout="responsive" src="{{ image }}" ></amp-img>
```

Then render the post content as usual.

```twig
...
{{ post.content }}
... 
```

**Comment by palmiak** [comment] 2018-07-18 08:05
@DrecDroid thanks for posting - I'll have to try it. Earlier this year there were problems with passing data to backend rendering, although Gutenberg was in heavy development back than.

**Comment by grantcodes** [comment] 2018-10-02 13:29
Just chiming in to say I have had great success with timber and gutenberg.

At the moment I have a solution that is very hacked together but works great. I use the method mentioned in the tweet above for server side rendering but inside gutenberg I managed to convert twig templates into react component and insert inline editors into them with twig.js to get a really nice experience in gutenberg.

**Comment by palmiak** [comment] 2018-10-15 05:52
https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/

Didn't test it yet, but I think this will be huge.

ACF blocks at last. I'll try to test it and create a acf cookbook section this week.

**Comment by addedlovely** [comment] 2018-10-15 08:48
@palmiak sadly not yet - seems to have been a confusing blog post - as that functionality has not yet landed - see https://github.com/elliotcondon/acf/issues/622

**Comment by palmiak** [comment] 2018-10-15 22:35
A short intro now, I haven't got too much time to play with it. In short - this is huge. @elliotcondon really made Gutenberg useful and easy to extend (thanks man).

Also - this tutorial is made for ACF Pro version 5.8.0-beta.1 - things can change, I'll try to keep up and change stuff if needed.

For start I just got the example used in https://www.advancedcustomfields.com/blog/acf-5-8-introducing-acf-blocks-for-gutenberg/ and "translated" it to Timber.

So first of all install Gutenberg, ACF 5.8.0-beta1 and Timber (I'm using the composer version).

Let's go to `functions.php` and add
```
add_action('acf/init', 'my_acf_init');
function my_acf_init() {
	
	// check function exists
	if( function_exists('acf_register_block') ) {
		
		// register a testimonial block
		acf_register_block(array(
			'name'				=> 'testimonial',
			'title'				=> __('Testimonial'),
			'description'		=> __('A custom testimonial block.'),
			'render_callback'	=> 'my_acf_bock_render_callback',
			'category'			=> 'formatting',
			'icon'				=> 'admin-comments',
			'keywords'		=> array( 'testimonial', 'quote' ),
		));
	}
}
```

with this we're adding a block to Gutenberg. Next add new field group and add fields just like in article. There is only one difference - the avatar field should return ID instead of array.

Now let's create a callback also in `functions.php`:
```
function my_acf_bock_render_callback( $block ) {
    $vars['block'] = $block;
    $vars['fields'] = get_fields(); 

    Timber::render( '/template-parts/block/content-testimonial.twig', $vars );
}
```

we're creating an extra array called `$vars` with two values:
- **block** - with all data like block title, alignment etc
- **fields** - all custom meta fields - also all the fields we created in ACF

And the last part is the template - `template-parts/block/content-testimonial.twig`:
```
{#
/**
 * Block Name: Testimonial
 *
 * This is the template that displays the testimonial block.
 */
#}
<blockquote id="testimonial-{{ block.id }}" class="testimonial">
    {{ fields.testimonial }}
    <cite>
        <span>{{ fields.author }}</span>
    	<img src="{{ Image( fields.avatar ) | resize( 150, 150 ) }}" alt="{{ Image( fields.avatar ).alt }}" />
    	
    </cite>
</blockquote>
<style type="text/css">
	#testimonial-{{ block.id }} {
		background: {{ fields.background_color }};
		color: {{ fields.text_color }};
	}
</style>
```
I think everything is pretty obvious here - as we passed two arrays (`block` and `fields`) we use vars like `blocks.id`, `fields.avatar` etc.

Some extra :)
If you would like to use a repeater - it would look like this (this field in not in the article on ACF - it's just an example of repeater logic):
```
{% for field in fields.repeater %}
    Title: {{ field.title }} <br/>
    Url: {{ field.url }}
{% endfor %}
```

**Comment by palmiak** [comment] 2018-10-24 09:58
@gchtr @jarednova what do you think about putting this into docs? Either as separate cookbook or part of ACF? I mean not the full article, but just the example with templates etc.

**Comment by elliotcondon** [comment] 2018-10-24 22:49
Hi guys.

I would be more than happy to include a timber article on our documentation. I'm half way through setting up our docs on GitHub so they can be contributed to by PR's.

Are you interesting in writing up a "Working with Timber" doc that can live on the ACF [resources](https://www.advancedcustomfields.com/resources/)?

This could cover the basics of what Timber is, how it working, using it with ACF, and also using it with ACF Blocks.

Let me know your thoughts.

**Comment by jarednova** [comment] 2018-10-25 02:58
@elliotcondon definitely. Do you have an example of a doc we could use as a model to get a good sense of the scope and granularity you've found most useful?

@palmiak do you want to take the lead on contributing the ACF article? I feel like you're on a roll with this one. To answer your Q: let's definitely add this to the "Guides" section of the docs. It feels distinct enough (combining a new ACF feature with a new WordPress feature) that it could be its own `.md` file — maybe with a link on the [ACF Cookbook](https://timber.github.io/docs/guides/acf-cookbook/) file so the two reference eachother

**Comment by palmiak** [comment] 2018-10-25 07:13
@jarednova no problem - I'll just need some help with polishing the words :) English is not my first language, but I think I can take care of the rest. 

Also I'll prepare this article as guide tomorrow or during the weekend.

**Comment by gchtr** [comment] 2018-10-25 08:59
A new **Gutenberg** guide would be great! It could explain how Timber works with Gutenberg in general and with ACF Blocks. I think what @jarednova proposed is a good idea. Because Gutenberg a topic on its own and the ACF Blocks feature is very specific to Gutenberg as well, it would make sense to have it in the same guide. We can link to the **ACF Blocks** section from the ACF guide.

**Comment by elliotcondon** [comment] 2018-10-25 23:46
@jarednova great! Take a look at the [Adding fields to a taxonomy term](https://www.advancedcustomfields.com/resources/adding-fields-taxonomy-term/) article as a good example of a "how to" showing instructions, screenshots and examples. I can imaging the "Working with Timber" doc looking similar, but with more code examples / text.

I'm happy to help with the content / structure too, but I'll allow you to get started first.

Can I ask a few questions about your docs setup?
- How do you like including a "docs" folder within the plugin? Does this make life easier or more difficult? Is this more convenient than using a separate repo?
- How do you handle images? Do you upload them to an "issues" via a comment, and then just copy the URL? For example in your [Debugging](https://github.com/timber/timber/blob/master/docs/guides/debugging.md) doc. This seems easier than managing them via git.

**Comment by jarednova** [comment] 2018-10-26 01:51
Cool! Thanks for the link. 

* **How do you like including a "docs" folder within the plugin? Does this make life easier or more difficult? Is this more convenient than using a separate repo?**
Highly recommended. Helps to keep us honest and simultaneously pay attention to both code + docs (at least, when we're on our best behavior)

* **How do you handle images? Do you upload them to an "issues" via a comment, and then just copy the URL? For example in your Debugging doc. This seems easier than managing them via git.**
Yeah, that's a hack we figured out at some point. Hopefully GitHub doesn't decide to do a massive image clean-up one day ...

**Comment by adiwebdev** [comment] 2018-10-26 12:34
Most of the discussion here is about rendering blocks with twig. I think might be other things to discuss as well.

- `dump` function render gutenberg blocks.
- Could be possible to access an array of blocks, similar to `post.audio` ? (it might be useful for post formats).
- `post.gallery` is not working.

**Comment by palmiak** [comment] 2018-10-26 12:41
@adiwebdev thanks for your insights.

- honestly I didn't check `dump` - I always use `function( 'var_dump`, blocks )` etc - I'll check it and come back to you
- If I understand correctly - inside of a block you would like to access all blocks as an array, am I correct? 
- `post.gallery` is not working on the Timber level or on ACF level?

**Comment by adiwebdev** [comment] 2018-10-26 13:01
I was thinking would be cool to be able to access the blocks inside the theme at template level (e.g. single.twig). Just like you use `post.audio`, `post.content` etc. Maybe something like `post.blocks` or `post.block('quote')`.

`post.gallery` should return an array of galleries found in post content, again, just like `post.audio` or `post.video`, it's not working when you create a post with gutenberg and add a gallery block.

It's all about using Timber at template level, nothing to do with ACF so far.

**Comment by palmiak** [comment] 2018-10-26 13:10
@adiwebdev  Ok - now I understand :) I have to digg more into the topic - I'm more into the ACF part right now. Although try to do some own digging and if you'll find something interesting share with us. We're definitely going to add some features for **Gutenberg** at some point. Probably the stuff with ACF integration will go first as it is the easiest to implement (thanks @elliotcondon once again).

**Comment by gsalkin** [comment] 2018-11-09 17:52
Adding to this thread for confirmation that Timber is marked compatible with Gutenberg/WordPress 5.0?

I've recently installed the 5.0-beta3 on my dev instance and my edit posts pages are showing a white screen of death. Disabling the Timber plugin allows the page to load but obviously then my theme doesn't run.

Are we now clearing people to make Timber sites using WP5?

**Comment by palmiak** [comment] 2018-11-09 18:02
Does this problem exists with composer module? I'll try to check myself
later.

pt., 9 lis 2018, 18:52: Gabriel Salkin <notifications@github.com>
napisał(a):

**Comment by chrisvanpatten** [comment] 2018-11-09 21:48
I'm using Timber with Gutenberg and it's working great. We have custom blocks rendered via Timber `compile` methods.

I'm not aware of any direct compatibility issues although I'm happy to help debug them — I'm a member of the Gutenberg team and have a pretty good understanding of the internals.

@gsalkin Did you get any particular error messages?

**Comment by gsalkin** [comment] 2018-11-13 15:20
No error messages in PHP, even with `WP_DEBUG` turned on. I do get some JavaScript errors in the console: 

`SyntaxError: Unexpected identifier 's'. Expected '}' to end an object literal. On post-new.php:3862`
`Failed to load resource: the server responded with a status of 404 (Not Found) This error is coming from the endpoint: localhost:3000/wp/v2/types?context=edit&locale=user`
`Unhandled Promise Rejection: Error function dispatchException On wp-polyfill-ecmascript.min.js:3:26016`

I have the sense that the issue is probably related to one of the second two errors. The REST api endpoints on my site should be /wp-json/wp/v2/types so is it possible that the REST API isn't configured correctly?

I also have no idea what role wp-polyfill-ecmascript.js plays in WordPress 5.

**Comment by palmiak** [comment] 2018-11-14 06:58
@gsalkin start from the top - syntax error. Start with typical debugging, disable plugins, use another theme etc.

Also provide us with some code.

In short - this shouldn't happen 😀

**Comment by gsalkin** [comment] 2018-11-14 16:22
@palmiak Well yes, certainly it shouldn't happen haha. 

Not to belabor this (obviously this is not a support forum) but based on my testing with disabling plugins, I think there *might* be an issue with the plugin version and Gutenberg compatibility. 

I'll work to switch to the composer module (is there a guide?) and report back.

**Comment by palmiak** [comment] 2018-11-14 16:28
https://timber.github.io/docs/getting-started/setup/#via-github-for-developers
just follow these steps and remove the plugin.

But when you mentioned, this is possible that are there are some problems
with the plugin. The plugin initiliazises in a bit different moment than
the  composer version.

śr., 14 lis 2018, 17:22: Gabriel Salkin <notifications@github.com>
napisał(a):

**Comment by ladislavsulc** [comment] 2018-12-06 22:04
@gsalkin had the same problem in general with Gutenberg - it was caused by a conflict with Soil plugin by Roots. Maybe this would help. Try disabling it.

**Comment by palmiak** [comment] 2018-12-27 07:46
@elliotcondon we have set up docs for ACF Blocks in Gutenberg https://timber.github.io/docs/guides/gutenberg/ (and there is a newer version https://github.com/timber/timber/pull/1884). 

You can use it in ACF docs if you like :) Of course if some changes will be needed I'm happy to help.

**Comment by landwire** [comment] 2019-02-09 08:28
> Just chiming in to say I have had great success with timber and gutenberg.
> 
> At the moment I have a solution that is very hacked together but works great. I use the method mentioned in the tweet above for server side rendering but inside gutenberg I managed to convert twig templates into react component and insert inline editors into them with twig.js to get a really nice experience in gutenberg.

@grantcodes 
I would be interested in your setup. Would you mind elaborating a bit or sharing some code? I managed to use timber for rendering the component/block on the frontend, but it annoys me to have to keep markup updated for a backend view in the react component and in php/twig on the frontend side. In my opinion there should only be one template!

**Comment by matthewattanasio** [comment] 2019-09-30 06:57
Bump for @landwire's requests @grantcodes

**Comment by cbirdsong** [comment] 2020-02-12 19:55
@grantcodes I would also be really interested in seeing this!

**Comment by gchtr** [comment] 2023-03-08 10:29
Closing this, because Timber in general works great with the block editor. In case somebody wants to share their solution, there’s a [Show and tell](https://github.com/timber/timber/discussions/categories/show-and-tell) section in discussions that would be great for this.

**Closed by gchtr** 2023-03-08 10:29 UTC
