### ISSUE TITLE
Timber initializing too early

### ISSUE THREAD

**Issue by haroldangenent** [timber/timber#1058] opened 2016-06-08 14:17 UTC
### Expected behavior

Timber to initialize after all plugins or mu-plugins are able to hook into WordPress functions.

**This bug is specific for `timber-library` (WP plugin), since initialization for `timber/timber` will have be done by the theme developer.**
### Actual behavior

Timber initializes before this happens (at inclusion). This is especially a problem in Multisite, because network plugins are loaded before `muplugins_loaded` is called.

Right now, plugins are forced to be a `mu-plugin` AND cannot use `muplugins_loaded` to register their actions. Possibly, Timber should even be initialized on `setup_theme` instead or at least at `plugins_loaded`.

**Use case**
Related to #1056: `Timber\ImageHelper::add_constants()` is run on inclusion as well (when initializing Timber). This does not allow plugins to hook into `home_url()` and change it.

The specific use-case would be when mapping a WordPress Multisite install to a domain. In this case, a filter should be used to change the `home_url()`.

_I'm not sure if the problem is as broad as "Timber initializing too early" or if it's a specific bug for this use-case._
### Steps to reproduce behavior

For the specific use-case:
1. Use WordPress Multisite
2. Create a subdirectory install
3. Map this website to a domain by filtering `home_url()` or using a plugin that does this
4. Sideload an image (for example, by resizing an external image)
### What version of WordPress, PHP and Timber are you using?

WordPress 4.5.2, PHP 7.0, Timber 1.0.4.
### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)

Composer via WPackagist.

**Comment by ChrisManganaro** [comment] 2016-10-03 09:08
+1

I've experienced the same issue when running Wordpress with [Bedrock](https://github.com/roots/bedrock), it changes the default content directory and install location for Wordpress.

**Comment by mahagr** [comment] 2016-10-03 09:38
+1

Its also an issue if you have Timber library installed, but local version in your own theme. Timber plugin registers and initializes itself as soon as the plugin php file gets loaded, which causes issues if theme uses different version of Timber.

**Comment by palmiak** [comment] 2018-11-06 07:56
@haroldangenent  @mahagr Is this still something you're actively working on or need addressed? Please respond in two weeks or we'll close this thread

**Comment by haroldangenent** [comment] 2018-11-06 08:14
Yes, nothing has changed so I believe this is still an issue when using the plugin. It should at least be documented that `timber/timber` should be used for multisites that use domain mapping.

**Comment by palmiak** [comment] 2018-11-06 08:19
I'm using bedrock with Timber and didn't had any problems. I'm also using domain mapping. The only difference is the fact I'm not using the plugin but the composer module.

I'm also using `"roots/multisite-url-fixer": "*"`.

Can you try using the module and this mu-plugin.

**Comment by mahagr** [comment] 2018-11-07 17:54
It's no issue if you're using Composer package, but you really shouldn't install the plugin or you're in trouble when it updates and you're still using the old version in the theme.

**Comment by palmiak** [comment] 2018-11-08 11:59
From what I know Timber 2.0 will be available only as a composer package.
So I'm not sure about fixing those bugs. Let's wait for Jared's or Lukas
opinion.

śr., 7 lis 2018, 18:54: Matias Griese <notifications@github.com> napisał(a):

**Comment by gchtr** [comment] 2018-11-08 13:50
> From what I know Timber 2.0 will be available only as a composer package.

Yes, that’s right. Releasing Timber 2.0 with the plugin version would break so many websites because of all the breaking changes. And Timber probably wouldn’t be accepted as a new plugin for version 2, because it’s not a "real" plugin. That’s why from 2.0, it will only be available as a Composer package.

Because the issue here is a case that can easily be circumvented by using the Composer package, I wouldn’t invest the time to fix this for the plugin version that will be outdated soon. But we could add a hint in the documentation for 1.x. Pull requests welcome 🙂.

**Closed by gchtr** 2018-11-08 13:50 UTC
Labels: needs-investigation, old-issue

**Comment by mahagr** [comment] 2018-11-14 06:44
@gchtr Well, the issue is opposite. If you have Timber plugin installed, Timber 2.0 based themes will not work. You need to uninstall Timber plugin to get them to work.

**Comment by gchtr** [comment] 2018-11-14 06:58
@mahagr That’s exactly what I meant or tried to say. Maybe I wasn’t clear enough.
