### ISSUE TITLE
PHP notice in PHP8

### ISSUE THREAD

**Issue by uprise10** [timber/timber#2461] opened 2021-06-25 08:30 UTC
## Expected behavior
No PHP notices :)

## Actual behavior
PHP8 is throwing a notice, because of incorrect declaration of function parameters:
>Deprecated: Required parameter $data follows optional parameter $sidebar in /{path}/plugins/timber-library/lib/Timber.php on line 462

## Steps to reproduce behavior
Just enable the plugin and check output/logs

## What version of WordPress, PHP and Timber are you using?
WordPress: 5.7.2
Timber: 1.18.2
PHP: 8.02

## How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
Via wpackagist/composer.

**Comment by gchtr** [comment] 2021-07-12 19:55
I’m closing this, because it’s a duplicate of #2450.

**Closed by gchtr** 2021-07-12 19:55 UTC
