### ISSUE TITLE
[Bug] Fetching posts by string (slug) returning unexpected data when post doesn't exist

### ISSUE THREAD

**Issue by philiprabbett** [timber/timber#1757] opened 2018-07-24 16:05 UTC
### Expected behavior
Instantiating a new `Timber\Post` by string (post slug) should return either the ***`Timber\Post` Object*** or ***NULL*** if the post doesn't exist.

### Actual behavior
Returns post object of first post in posts collection, assuming this is coming from `$wp_query`.

### Steps to reproduce behavior
Create the following two files with the corresponding code and notice the slugs don't match up.

```
<?php  
// single.php, see connected twig example  
$context = Timber::get_context();  
$context['post'] = new Timber\Post( 'fake_slug' );  
Timber::render('single.twig', $context);  
?>  
```

```
{# single.twig #}
{{post.slug}}
```

My workaround at the minute is to first use `get_page_by_path`, check if that function has returned anything other than ***`NULL`*** before passing all it's data into the `Timber\Post`

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.7, PHP 7.2, Timber 1.7.1

### How did you install Timber?
Composer/Packagist

**Comment by palmiak** [comment] 2018-07-24 20:54
From what I see in the docs = `__construct( mixed $pid=null )` so you can either pass null or post ID.

**Comment by philiprabbett** [comment] 2018-07-25 09:14
Yes but the inline docs within the `Timber\Post` class indicate that we can use slugs also (see `prepare_post_info()` and `check_post_id()`, unless I'm mistaken? I mean, the workaround I have means passing an object into the `__construct()`.

https://github.com/timber/timber/blob/master/lib/Post.php#L360

**Comment by palmiak** [comment] 2018-07-25 09:40
You're righ. I'm looking at `get_post_id_by_name` in PostGetter because this is the method that changes the slug to ID and when you pass the fake slug it returns NULL and when the NULL is passed than Timber\Post gets the current query post.

So it's on your side to be sure that the slug exists (like the way you are doing). When you are sure it exists than pass the slug/object.

**Comment by philiprabbett** [comment] 2018-07-26 16:30
I'd have expected it to return `null` rather than the current query post. Am I mistaken on how I expect this to work?

**Comment by palmiak** [comment] 2018-08-01 12:30
@philiprabbett is everything clear? We can say that it works as it was intended to work.

On the other your right that it would be more logical that if the sług doesn't exist it should return FALSE instead of NULL. So the Timber\Post would  also return false instead of latest post. 

It's not something cirtical, because we can always write an extra if and everything will be OK. Still try making a PR for this.

**Comment by palmiak** [comment] 2018-10-24 14:10
@philiprabbett I'm closing this for now - if you'll have extra questions I'll open it again.

**Closed by palmiak** 2018-10-24 14:10 UTC
