### ISSUE TITLE
Custom post type edit page shows default posts instead of post_type and throws two array to string conversion notices

### ISSUE THREAD

**Issue by sctgraham** [timber/timber#1889] opened 2019-01-03 13:44 UTC
### The problem 
This is an admin problem with no effects on the front-end.

All `edit.php` pages in the back-end throw the following two notices :
`NOTICE: wp-admin/edit.php:266 - Array to string conversion`
`NOTICE: wp-admin/edit.php:364 - Array to string conversion`

In addition to this, any post_type edit pages (in my case `/edit.php?post_type=page` and `/edit.php?post_type=acf-field-group`) display a list of `posts` (i.e. articles) instead of the designated `post_type`. these admin pages throw the following notices

Disabling the Timber plugin makes all the above issues disappear.
The issues remain if I disable all the other plugins and leave just Timber as the only active plugin.

### What version of WordPress, PHP and Timber are you using?
Timber 1.8.4, Wordpress 5.0.2, PHP 7.2
Also tried reverting to Timber 1.8.0 and 1.7.0 and Wordpress 4.9.8.

### How did you install Timber?
Via Composer with Wordpress Packagist

**Comment by Levdbas** [comment] 2023-05-12 09:58
Just tested this myself and I cannot reproduce this at this time in Wordpress 6.2/PHP8.0. Closing for now.

**Closed by Levdbas** 2023-05-12 09:58 UTC
