### ISSUE TITLE
⁉️ COMMUNITY INPUT WANTED: Timber WP-CLI support ⁉️

### ISSUE THREAD

**Issue by acobster** [timber/timber#2364] opened 2020-11-05 20:00 UTC
We need input from the Timber community to answer a very simple question:

**Do you use the `wp timber` command?**

Please react with :+1: if you do, :-1: if you don't, and as always, feel free to leave a comment. We want to weight the usefulness of this WP-CLI tooling against its maintenance cost.

**Comment by acobster** [comment] 2020-11-05 20:03
Discussion around this started here: https://github.com/timber/timber/issues/2323#issuecomment-721387388

**Comment by stewarty** [comment] 2020-11-06 12:13
I'm an almost daily Timber User and I don't think I have _ever_ used the CLI command

**Comment by 19h47** [comment] 2020-11-06 16:11
I use Timber in my everyday routine and didn't know about the CLI command 😅

**Comment by szepeviktor** [comment] 2020-11-06 17:59
> didn't know about the CLI command

@jarednova The root cause may be the lack of information.

**Comment by AshleyRedman** [comment] 2020-11-06 18:22
I also use Timber nearly daily and have never used it, but only because I didn’t know about it. I’m surely going to look into it and any good integration with the cli is a positive to me.

**Comment by xavivars** [comment] 2020-11-07 09:49
I didn't know the command existed either...

**Comment by kristjankoppel** [comment] 2020-11-07 18:47
Voted down but also would like to refer to lack of information about it. Talking about it and showing it in action would be helpful and also would motivate to use it.

**Comment by landwire** [comment] 2020-11-07 19:59
I did not know about it either. But would like to try it out on my next project.

**Comment by jarednova** [comment] 2020-11-08 19:06
Thanks all! It's clear that this isn't being used in its current incarnation. It seems that there's a fair amount of sentiment that this _could_ be useful (will need docs!). I think the next step would be to pull this into its own repo within the timber org and continue development (and docs!) there.

I know that @gchtr, @acobster and I are all wrapped up right now with the 2.x release so consider this a big 🏷️ **Help Wanted** opportunity. Feel free to raise a ✋ if you're interested in maintaining that sub-project!

**Comment by xavivars** [comment] 2020-11-08 20:19
@jarednova : are you talking about this?

https://github.com/timber/timber/blob/master/lib/Integrations/Timber_WP_CLI_Command.php

**Comment by jarednova** [comment] 2020-11-09 14:27
@xavivars yep! well, that's the start at least. I'm honestly not sure what the best functionality would be to include for WPCLI (caching? image regeneration?)

**Comment by acobster** [comment] 2020-11-09 18:59
> image regeneration?

`wp media regenerate` already does that. Is there a special Timber layer of the file generation piece that I don't know about?

One feature I could see being useful to the community is scaffolding for generating sub-classes of `Timber\Post` and other core classes:

```sh
$ wp scaffold timber-post-class MyPost --namespace=MyProject
generated class MyProject\MyPost in src/MyPost.php
$ wp scaffold timber-post-class MyTerm --namespace=MyProject
generated class MyProject\MyTerm in src/MyTerm.php
```

We could even leverage Twig to do this.

**Comment by acobster** [comment] 2020-11-09 19:13
@jarednova also, I want to be clear that I still don't see a compelling reason to split this functionality out into its own repo, at least not yet. It seems like a lot of extra maintenance work for not much concrete benefit (at least that I can see - maybe I'm missing something!). If it turns out is does "want" to be its own project, I think it will tell us because the complexity of managing it here will become obvious and unsustainable. But FWIW, I don't think that'll happen. I've authored a handful of plugins with their own WP-CLI tooling now and it has never even registered as a problem: if a maintenance bottleneck does show up, it's always elsewhere.

**Comment by TheVrai** [comment] 2020-11-10 16:43
I'm a daily user of timber (thanks for the great work), I use it with roots/bedrock and with wp cli.

**Comment by gchtr** [comment] 2021-01-13 21:01
> > didn't know about the CLI command
> 
> @jarednova The root cause may be the lack of information.

I can definitely work on better documentation.

> I want to be clear that I still don't see a compelling reason to split this functionality out into its own repo, at least not yet. It seems like a lot of extra maintenance work for not much concrete benefit (at least that I can see - maybe I'm missing something!).

I’m totally on @acobster’s side here. I wouldn’t move this to another repository.

> I'm honestly not sure what the best functionality would be to include for WPCLI (caching? image regeneration?)

Deleting caches is surely helpful.

> > image regeneration?
> 
> `wp media regenerate` already does that. Is there a special Timber layer of the file generation piece that I don't know about?

There’s a function for [deleting generated image files](https://github.com/timber/timber/blob/master/lib/ImageHelper.php#L266). A can image that a CLI command that can delete all generated image sizes could be helpful. When pages are loaded, image sizes would be generated again automatically.

> One feature I could see being useful to the community is scaffolding for generating sub-classes of `Timber\Post` and other core classes

Nice!

**Comment by NazimHAli** [comment] 2021-12-19 15:52
I voted down, but would like to try it. Didn't know about it :sweat_smile:

**Comment by gchtr** [comment] 2022-08-05 13:23
Good news! I reintroduced Timber’s WP-CLI integration in #2611. There’s a new [WP-CLI Guide](https://timber.github.io/docs/v2/guides/wp-cli/) that you can check out. Feedback welcome.

It’s included in the [first Beta](https://github.com/timber/timber/releases/tag/2.0.0-beta.1) for Timber 2.0 that was just released.

For now, it only includes the commands it included before. In this thread, we shortly explored other ideas for future commands, like scaffolding Timber classes or deleting generated image sizes. If somebody feels up to contributing new commands, we’re happy to accept pull requests.

I’m closing this issue. Please open a new issue or discussion if you run into errors.

**Closed by gchtr** 2022-08-05 13:23 UTC
Labels: has-patch, dev-feedback, 2.0, wp-cli
