### ISSUE TITLE
[BUG] Twig 3.10 breaks Timber

### ISSUE THREAD

**Issue by rmens** [timber/timber#2993] opened 2024-05-11 15:08 UTC
### Expected Behavior

Timber to work with Twig 3.10 that is allowed to be installed according to the included `composer.json`.

### Actual behavior
```
Fatal error: Uncaught Exception: You must call "setEnvironment()" before calling "Twig\Extension\EscaperExtension::setEscaper()".
in /home/zwupdate/domains/redacted.nl/public_html/wp-content/themes/streekomroep-prod/vendor/twig/twig/src/Extension/EscaperExtension.php on line 127

Call stack:

Twig\Extension\EscaperExtension::setEscaper()
wp-content/themes/streekomroep-prod/vendor/timber/timber/src/Twig.php:558
Timber\Twig::add_timber_escapers()
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters()
wp-includes/plugin.php:205
apply_filters()
wp-content/themes/streekomroep-prod/vendor/timber/timber/src/Loader.php:518
Timber\Loader::get_twig()
wp-content/themes/streekomroep-prod/vendor/timber/timber/src/Loader.php:120
Timber\Loader::render()
wp-content/themes/streekomroep-prod/vendor/timber/timber/src/Timber.php:1444
Timber\Timber::compile()
wp-content/themes/streekomroep-prod/vendor/timber/timber/src/Timber.php:1579
Timber\Timber::render()
wp-content/themes/streekomroep-prod/single.php:222
```

### Steps to reproduce behavior

1. Install Twig with the composer.json that ships with the project.

### Notes

Added `"twig/twig": "3.9.3",` to my composer.json to fix it for now.

### What version of Timber are you using?

Timber 2.1.0

### What version of WordPress are you using?

WordPress 6.5

### What version of PHP are you using?

PHP 8.2

### How did you install Timber?

Installed or updated Timber through Composer

**Comment by cronin4392** [comment] 2024-05-12 02:15
Ran into this as well and downgrading twig worked as a work around for me.

**Comment by gchtr** [comment] 2024-05-13 06:43
It looks like this was already fixed in Twig version 3.10.1 (see https://github.com/twigphp/Twig/pull/4083 and the [Changelog for 3.10.1](https://github.com/twigphp/Twig/blob/0bdc73a5997fe0ab16ec44dc46351bc66edf7496/CHANGELOG#L5-L8)).

Can someone confirm this fixes the Fatal Error?

There might still be a deprecation that we might handle. Maybe we need to register Timber’s escapers differently, so they don’t break in the future. I didn’t have the time yet to investigate further, though.

**Comment by pgnd** [comment] 2024-05-13 10:54
confirmed, here

with
```
composer show twig/twig | grep version
	versions : * v3.10.1
```

all good

reported in # https://github.com/flyntwp/flynt/issues/554

**Comment by rmens** [comment] 2024-05-13 20:51
Can also confirm that Twig 3.10.1 makes it work again. Great to see quick patching of the deprecations too! 👏

**Closed as completed** 2024-05-14 07:29 UTC
Labels: has-patch

**Comment by samuel-hauser** [comment] 2024-05-15 08:32
Cannot confirm that it works. Installing with composer, adding classes via psr-4 like so:
![image](https://github.com/timber/timber/assets/3699017/4a339199-28c1-440e-b413-782fd80308e2)

except: there seems to be no class for the deprecation contracts.

sooo: tried to load the deprecation contracts in php (via require_once)

PHP error:
`Uncaught TypeError: Argument 4 passed to trigger_deprecation() must be an instance of mixed, string given`
