### ISSUE TITLE
Uncaught ArgumentCountError when using an action

### ISSUE THREAD

**Issue by merijnponzo** [timber/timber#2577] opened 2022-04-27 08:53 UTC
Since do_action is not in the v2.0.dev documentation
I had some problems with implementing a WPML menu

So (from the 1.0 docs)
```
{% do action('wpml_add_language_selector') %}
```
Results into an error while using Timber 2.0
```
 Uncaught ArgumentCountError: Too few arguments to function WPML_LS_Actions::callback(),
```

Adding an empty string as an arguments solves the problem
```
{% do action('wpml_add_language_selector','') %}
```

Or wrapping the action within a function:
```

function ponzo_wpml_menu(){
    do_action( 'wpml_add_language_selector' );
}
```
In template:
```
{{ function('ponzo_wpml_menu') }}
```

**Comment by Levdbas** [comment] 2022-05-05 09:43
Hi @merijnponzo , it seems that you need to use the new `wpml_language_switcher` action instead. See `classes\language-switcher\public-api\class-wpml-ls-actions.php`. This action does requires two arguments. `wpml_add_language_selector` is marked as deprecated.

**Comment by merijnponzo** [comment] 2022-05-05 13:02
Thanks @Levdbas 
```
{% do action('wpml_add_language_selector') %}
```
Results into the same error unless you add some empty arguments within the twig action.

So
```
{% do action('wpml_add_language_selector','') %}
```
works

**Comment by Levdbas** [comment] 2022-05-05 13:13
`wpml_language_switcher` seems to take 2 arguments. So that would explain the error: https://wpml.org/wpml-hook/wpml_language_switcher/

**Comment by gchtr** [comment] 2022-05-05 13:19
I can give some insights into why this error happens in Timber v2. I think the error your running into comes from the following change we made in Timber v2: https://timber.github.io/docs/v2/upgrade-guides/2.0/#no-context-argument-when-calling-actions-in-twig

In Timber v1, Timber always adds the context argument as the last argument to the hook function. This led to unexpected behavior. I guess that’s also why before `{% do action('wpml_language_switcher') %}` worked, because Timber passed in the context array as an argument. The `wpml_language_switcher` action actually expects an array as a first argument.

**This error is very much intended behavior in v2. Adding an empty argument is the correct and intended solution:**

```twig
{% do action('wpml_language_switcher', '') %}
```

As @Levdbas mentions, the [`wpml_language_switcher`](https://wpml.org/wpml-hook/wpml_language_switcher/) action expects an `$args` parameter to be passed. The `$args` parameter is required. You need to pass it in. Here’s an excerpt of the callback in the WPML plugin uses for this hook:

```php
/**
* @param array       $args
* @param string|null $twig_template
*/
public function callback( $args, $twig_template = null ) {
    if ( '' === $args ) {
        $args = array();
    }
}
```

**Closed as completed by gchtr** 2022-05-05 13:19 UTC
Labels: 2.0
