### ISSUE TITLE
Timber 2.x render caching is broken

### ISSUE THREAD

**Issue by silentdragonz** [timber/timber#2646] opened 2022-10-05 21:42 UTC
## Expected behavior

Pages to be cached as their own transients when using the cache.

## Actual behavior

One transient is used to cache every page leading to the wrong page being returned from cache.

## Steps to reproduce behavior

Use a theme with no parent and the render cache.

## Fix
https://github.com/timber/timber/blob/1b91b3c31589162b2bc1872d0ff946fa7b68665d/src/Theme.php#L125 This line causes the context object to have recursion which means the json_encode for the cache key always returns false so every page has the same cache key. I saw this was added in #2264 to resolve other issues, but removing it fixes this issue.

**Comment by gchtr** [comment] 2022-11-09 07:31
Thanks for opening this issue 👍. I just added a test that confirms this bug. And I can also confirm that the recursion is what causes the problem. Now we only need to figure out how to solve this best.

This issue #2429 is a duplicate of this.

**Comment by gchtr** [comment] 2023-02-02 16:07
Fixed in #2675. This will be in the next 2.x release (hopefully soon).

**Closed by gchtr** 2023-02-02 16:07 UTC
Labels: has-patch, 2.0
