### ISSUE TITLE
Bug with latest release

### ISSUE THREAD

**Issue by bwalker5** [timber/timber#2655] opened 2022-10-19 18:27 UTC
We received the latest Timber update last night 1.21 and our web site wasn't available after that (error message on page). The issue was resolved by going back to 1.20. 

Here is part of the error that was in our WordPress logs - PHP Fatal error:  Uncaught Error: Class "Twig_Filter_Function" not found***

**Comment by GaelenN** [comment] 2022-10-19 23:52
Also having this problem with a client site.

**Comment by mrfsrf** [comment] 2022-10-20 06:58
you have to specify more information. Did you install Timber using composer and than switched to wp plugin version, or vise versa?
Have a look at the timber starter theme functions.php

**Comment by gchtr** [comment] 2022-10-20 07:07
We have a pretty good idea where this is issue might be coming from and are currently investigating.

**Comment by bwalker5** [comment] 2022-10-21 20:49
> We have a pretty good idea where this is issue might be coming from and are currently investigating.

do you need any info from me to help troubleshoot the issue?

**Comment by jarednova** [comment] 2022-11-08 04:12
@bwalker5 if you're interested in lending a hand, we just published to WP.org. Are you able to download and verify in one of your setups?

https://wordpress.org/plugins/timber-library/

**Comment by gchtr** [comment] 2022-11-22 16:49
It looks like this is the same issue as https://github.com/timber/timber/issues/2672. It will be fixed in https://github.com/timber/timber/pull/2679.

For a very quick fix you could use

```bash
composer require twig/twig ^2
```

**Comment by gchtr** [comment] 2022-11-24 06:18
We just [released a new 1.22.1 version](https://github.com/timber/timber/releases/tag/1.22.1). Could you check whether you still have your issue?

**Comment by Luckyfella73** [comment] 2022-11-25 14:48
@gchtr  I can confirm that my _Unknown "filter" tag_ issue is solved with TimberTwig 1.22.1 

Thanks for fixing the issue that fast! 🙏

**Comment by jarednova** [comment] 2022-11-25 22:32
Great to hear @Luckyfella73 ! thanks to @rmens for submitting the PR to help us here

**Closed by jarednova** 2022-11-25 22:33 UTC
Labels: has-patch, 1.x
